---
# Area
- { name: "area/github",             color: "0e8a16" }
- { name: "area/kubernetes",         color: "0e8a16" }
# Renovate
- { name: "Renovate",                color: "ee0701" }
- { name: "renovate/container",      color: "027fa0" }
- { name: "renovate/github-action",  color: "027fa0" }
- { name: "renovate/github-release", color: "027fa0" }
# Semantic Type
- { name: "type/digest",             color: "ffec19" }
- { name: "type/patch",              color: "ffec19" }
- { name: "type/minor",              color: "ff9800" }
- { name: "type/major",              color: "f6412d" }
- { name: "type/pin",                color: "#ffec19" }

# Uncategorized
- { name: "automerge",               color: "ee0701" }
- { name: "system-upgrade",          color: "5319E7" }