apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:xXrBbDSADz0bTJyyRe7FUEL0vQEalH7z/X2iufLkqV+xtH+NzQ7lJwZQnwNv6juDYfs2rf8jjvogK3tTpHTwl8wWYuaICtIbbiF74gOTrEs9/dMlG02vHSYB43jTvTaixQScsaoc+9IFTiy1FVSenCbLgt+wvC8K8A==,iv:CYOSgY6fKUKuJcRVxQA+Fa7JEyXZfixAIfdXIzlMw9Q=,tag:7dlIWXpnTzSv8ZH0WdKNeg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbkx2Tm5TRFVoUVVMSzA3
            Q3dnQ1BYVmlXYitRbldkR095OEt3UUtnYmpjCkJjVXNxd2h5OEFsVkpUNWk4dHI3
            U0tNc2wzZ01ma3czUlVNbHd3bWlxemsKLS0tIE0xS3NzeEVjT1BiNWM1VkI3YU83
            VmtNcFRCYlVlMXlkMkFwb3lBWGdHV0kK1ZCy6sm44wCHxPEZ1niWwx6tiDBbRzrk
            VH0X5fcJheK5kq27giEYudtC/p7T6gYDEUQ3Af9lDtwn1g18vdKsdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T10:31:32Z"
    mac: ENC[AES256_GCM,data:a3NMVZN8k1fzUBDuRJXhgLz/Fvc1uM9Srj2APaczS+aBw6oXwKsaB9+Fx2btTU2u33k0RARpW9nQdFEttpI1RcIYzA0HwYo68FjgU6bfgE+nTBAON/SMVl5Wc/ElPt2t1MEY9uVg7UQhryeNI+PtUiHfRiHonLMYn0upR68Took=,iv:4kH08ioo5mctD+eoeGn0iiKljQ1N4zpU20Ir15Yi5h4=,tag:x+wf3VIeVCZGY34zjzECfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
