apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:71f0CPwbkRIObYmZj2UIrPXA6l5bhez8+LyRIjN/D9E72ZT+5YJhutKsbxf/scp2JkMsyJOOe2JjQyIAUldE2VqNWMJBaZnW61oi0ZaTp8+b25Jdt79H2RNgQ85aHVnqNu44niSDfE9dircaZGsGaEFoaSZ0aBZFNA==,iv:oQA0ir7ppaIsnppP2J9BJHlIOJocEUuCYFxRWA3E4js=,tag:2F910IRm2M1WEvq1x9Lo6A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dlkzbmR4bmdwcWduVjRp
            M0FuK0UrMHBkUEp3TDdXRU5vcEtzUEVkQmdBCmN5a3dycXNxZUJ3M3ZhMkxkNUov
            WkdBQjg0WTZUSG5vTmFob0E1N2laWkEKLS0tIGJabDByV01tcHNEeGxIcmw4bnVH
            OEt1cHBDSzZlcUQ3Um9oZWpWTkhjSnMKw5CTJQbnEs7NJRME+50vy+pc6eDwJlwi
            Qkd5OYS28IWKVg26WIzCPle3XDjxB1zMMDcmJtEBOgcL9KL7MY4m1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-03T22:54:32Z"
    mac: ENC[AES256_GCM,data:N5xZnPSJbPGEtIU2gyRCVwNCE1pST+KvokGscm5UVpDNUrNNxgPFXwQcAb0ZQqp0sBd2XDSAqm75ONKFjM03P5p2hDOzPBqnYsviL24T8Q8jBP9Mm6qXBpebf6mv9A0wvbrUBxqE/bRUPvqV69sdBcX7TR3hF87AFI1IbnNu7rM=,iv:mTYQ/UwIjgGT5dvptFjMbxa7SeTHrmueEDR0/TXglYg=,tag:eyruTXvSVaLqHV2e1feDbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
