apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:f/Gn1uPllwcDdPF9/6tvIDAymGNU7gaswp/1qDJ/6r0oijrLK5w30QeThtFrlWwJNsdOIO2m+d9PIeXhbyMEQneBdkFRfK0F3l28ufylhh5PdDkPKfaMUEGYfJUdx+Xf3jkcV41hkrOaS0Nz+zCbygS3JlzKuI9ZPg==,iv:idcQP72sNle+jvvBOpf8lpaq4NSUG5CfbFjPWWSDu7c=,tag:SoKYZx0DhC3zN1ryC76PwQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocWVYVW4rZllGcUtrMmNk
            VEhYejdMZzBCZ2xzS1ZVeFVtQ2hoWElFZWdrCnZkMHJuUXdhem92SFZRNy85L2kv
            UFJhZnNMVnlVcVJCVTNwVEF2dzVzM1EKLS0tIFBRUy91K0xaMFhmaGNnbVk4NnE5
            eUhacW53THJ2NFcvaXFaTWh6dGtEM2cKa0JJ2j0gG4W8KkAbdx54DyxpgeaJAkLM
            86eHHx/MYqBbgnxd8dAHhtsxlIH1lKSAi6bpf6cKhx6Y3PxmLFYMaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T10:30:36Z"
    mac: ENC[AES256_GCM,data:30GDgYjPNlq/C9NkOwedMDBCIalojtnnw+XKqb7qcAkyuaYYwOr15PxEgEcdsOd8V+EurhF3il7WPjD6Ag3xaW+2W6Ldt6XQM/BhFBGLnhq+rkeOg3iuHgM/Mj5QFP30S2tGtiztKYbb7aaUfx/WjI41tVwaZ47BrAAG54+teHQ=,iv:4MNIY84CcWSfiNAfSSHy01eKyWhBvRvOVj3KDHSr5ek=,tag:XD2ninvZ16U8Ly3M1pZoTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
