apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:rT8frJ9Djk3Ns2VdmxNSgW96b7yTa+HfyP+/hhe2E23OwKlwy6vz7COZ1V8gRHCDuPaHxKNy4E8Z4ymPNcK1uJYbMLGO0Kt/nD4+tmUxtfHq38Q97MKQtpl8aIfY0gegZ1wtC2299hCW3tzIibtmKK7SuwOOUnjkmg==,iv:/lLmKUSuEWVm9iWjG6Pee2+A/CjRmprMJKl+167pppI=,tag:6J4hJLtR4WeDUWnXMkmD2w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUnB6a3RIZFl2cllURjBD
            bnhjUlpUYWJtckpxc3lYNWY5a2dIQlVHMDFZCnZzcUd1c2xocG5pZjlhVk50OEFK
            ejl2ZFBaK0pjL2VlcEJNUWV1UDR3ZmMKLS0tIGJsdk5PemtNbTVaYmgxNnNGbkJB
            M3p3VG5kZjNRNGc2bUhLNzVORTI3T00K2ZXXT0Now3c3w0EcT3UitFXRZ1sPu8bz
            2tZe8p15fBvxWRdQxawq9/i5THzS2TwCJ9Pa6mV0CsGGoVYSA7n/2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-20T10:18:45Z"
    mac: ENC[AES256_GCM,data:+JdsyiZ60uwnk7foSjCNXJ6tJibhaU2MUcwxAWKoyX42P5gh2jySfTlNNRxiaG/uUmTO+CUMvwTqBjSBmjIH5P/kLzCk/9A6M1AiO1ds70E7iZrVM79aEDTMl4jcwyTFp80M2vTi1HjUC+scig2Af0Ta+xiH9NpKbkNIYr9yHhY=,iv:m3aElHFMkQzL7eNXG37tnV30TF/AFFQ7HcMz2s6MPgo=,tag:8S1hPha2RWLBbyLoZk3jng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
