apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:XJi7h1A7qIxud5ufyDu1ZCttkSIKQkaEvdtkPAZXDqLBtYRFSYFCLTp16FhM2dCcaj7iG5nc2oVC7gHSWZGPtwxvrqDAliTXf8jX7DI7HtHcOuBUrgN731ql3o/rdO10DgcvUiDUoTgipjMVuFdC2cXXUcqpYCGSrw==,iv:je3stOVZtCWCeIECEu7HKTPZW5VWkTtkYrW0W+6fJdM=,tag:E4GDsRKCHTuf4wiKQAHIZQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQWJwdzV5N2wxTFRkUkZC
            V0FqTGIwbC9KWGZxWlVGTk14Y2tvaFpJK1YwCjVVaHpmVzBqMVczZDg4OUtJWmF2
            a08vVmpLVXRqYkR6SUJYUS92eWhrUlkKLS0tIG8xbEx2di90NXZpZnBvdUtoT1JF
            Y1FhdHdCRXpUODBhRWxybmF6MlZKNmMKgfSfR0Q5S7UH1KW5/LZ7jLFdk3q1vF3F
            b+iEd97hFG3ao1HbSRq+RxpPx70E5pncsm83vFEFP0U8l2ov83KeuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-08T11:50:07Z"
    mac: ENC[AES256_GCM,data:EUJpKM05TgyErnlt6pcYzS0qQpzlw7D41e4iME85Ca4209DYtuydfB9qrcw0BISrM1l+OZgiCVICEo54w7EkJNY/FvwL3n+HIar0Ml+rklsuZJWvBzk9+6lEa/+ba/zdpYV/ntpbJc9jpFWHXkk0Z3dvoFliTKa1IQOtGvJqonY=,iv:RV1YQ2rw5Rx6i5wANO7SCCJ5kAZ3hZOgMBw/C8jih/g=,tag:Et9JP2p+MOybXv8/i26yBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
