apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:7DmUy+fy6hudMUaENhFXhSeFHED1/FkriqzF2ZRqgaVNqDT+Hq0qPtXpz6+GxQBSAypMoGAsRTUuU8Avdl3/X5+dKuYkcOtF0aSBMIpnJ1dT6ky2My541WjKXgk8Lh+h+2A4tvK+9CtWweeOYuI0TOtBKM6YdbtbVQ==,iv:qzUqlgsINeNkscIY+gb+r9gOv16+pP7UUTqzF4WFbRk=,tag:yvwHgEVxsJhusNByUjAgkw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S2ZiRFF3QU0yL0o0OS9y
            S012dkxXNXg2QWtJdDBsanpSZXBWYjVUWVhrClNxMkZOWkEvOUJBZFVkWmp1TXFQ
            SW5xUFNLaFQ1STJCWjArclhWK0hGWTgKLS0tIEIrUWJ4WDFHZTBKU2R6L0wzOWd4
            dUVlbVY3ZU5UNVo3cmYzMHBOOUxhWncKV50Ga9TuwnAJvWw9yqiOwlahQZzrskjQ
            g6vzwRDLh520pZHP8Xj4AAATbk5ycHIfaR3Fc23wR12fGrhscBv4tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T07:51:22Z"
    mac: ENC[AES256_GCM,data:zyduZoFm4JNceJ65V6JGXmr7Tvl/T7jkXMgOOKt3t2oxVAgkrCJ0iqjZ4rJ+gZIA9uuWUh2YRTgWS+QrOLXM98FWZVzMRkzDkTkSSshISy5o7a8zaJWsAqvsgivrhiIP5aLFN3EZXz2QyMuZnDcymvoPasZHMGRB85DSYA6cGx8=,iv:H4HMRShByzxU666f+sePaZ3uqQgSvv8iAACn/MDuzBs=,tag:YrxBX/I7sgMUIJxou2e7YQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
