apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:vbnl64YPoCyXHb/8N2dr3NHVAK/tDEqJtdIakS39YPJMq7MC10Ku7BE4ws6u6juyoPc3Gnh60FQ3Hw4dzDSdLISICXE+TET4yF5BvFdX+E43IA4uLYynICu7hFgWr8jAlOLEjtcwrB6JBibN5LaCiSOcsb7tkJNpeg==,iv:kFAsNtQqfORzm5ckTVpDhUG1/yBknKTf8AgnvDB2rdE=,tag:BCfyopGtPQsnLY3msjxTmw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSWo5VCtQYUFDQzl2aURq
            d3pnY3daQlU1K2w1Y3pRcE01MytKQUM4dmxzCk5XbktKTUdiUm8rOFBhK093S2dG
            SEV1SkJDSWtGaUtOclA4TEV3Q1J2a1EKLS0tIDhDK1VNblVZUzlhUUZkUFNaazRD
            WmhwOWp6djdieW5HOHhqc1BPL3dOdlEKjIjJbTKH9KqealWy8IiW7vPmc9QEqppP
            wzIeV1AHmFLrHlHG0MHyNrb41tHkLxKaUCO+Xz9DVCzVzvoGZvs8Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T12:35:56Z"
    mac: ENC[AES256_GCM,data:D+klhInnXeKH5sgRbPV3Kz2JwtRDzE0tZyJGoOXtmJbIbcjiiCG6p4O9gxogt/X1eFE74KpkvJ3F/+hOLHSOQf6BBtmbHUjivegcsWcAule2Ve+TO2I2Z28cZy1A4WNhoyx8bbQ0V0Rnij14GhJBFM9Pl9EKmqCAmqJeyycBDsQ=,iv:xW3wU+GzNU3M7Q3y4dV9XXhZQTa1w+uljUF5ZWZE8FM=,tag:sPcQ/R9IrHmRUeLkRBPvIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
