apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:Kzd7uHabgdvcWI7OUfbtAIrS0qtNnj+E+3knIm/yi1Ivn+q5KUqNYnN9pVF9KhW/Xl9jbbxwpCZ5/h83bIIVhQdJJTaHrl877RskVU/8QRdxNp7cKV378oF1u2hR85OKF7vxFaENiT7c0V1Jh6WwX0J2T2/Po4I3mg==,iv:+efoCpQJmoznqa4Tfre7KzFZECMQJVF+352G4xj7d18=,tag:+njwS0u8EuNA95A/3vV75A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVDBtUEUrdTJJa3VzVFlx
            MUY1NCtnZDhWSFpYY2lTY0QxRVBpN09nWGtjCnF4L05abk9kNVBEQXRVcVdKTjZI
            YWYrRGxYRWxYbEdnd3Z0TEord3hwQzQKLS0tIFVoZkZrV0l3dzQxdVh1QXVGSGJM
            azJiZWpDSFh5aHhpTTgzanZxdUwrdEUKc2zYw6kItgMRxgE21Uyqv9yhTmzYjIux
            kGhaA5HcP4cvexde60ox/W/1Yqaznv87vnOEtMTEKP3emg8ooae/AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T11:59:22Z"
    mac: ENC[AES256_GCM,data:+bxTAQoVZHMpkuVK2VD1nNRNzHZcZni0I1O3Wi2JST3AVLlyOsuAIc0+xESFQkSb9K6c5DYOoFWL6RIjR0yJBVvBkAep4tP3ROOsdYDCCBKhqacCJ4LM+Fv3T74d+Sf09QyD939IK/q1C8ORIB7xgR5TkUkU+ibf7qrs4UMwTPE=,iv:wuRzE9mS0dQmS6SXjOVQwaSd3p1gH+boFCn/2+sdib0=,tag:jLdcf7BZlKIW03SDs7ukEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
