apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:Jixk/4Jsi8KrKcQWBic0nxsb9zuviLhjv/TivnlYnQND8D20OrsgGLeMjAy+u6KplgUvSUoYzPVoPsqAC04M8rj/IpI6qEKvRyT8COvbkgu4oCSewbLyGTPu0K/QcoYiZ+BGXFkhB7NzOZRXuGHrHvZrbO3KKLCLcQ==,iv:0FF0rv5r9KrMOYLGkf/Q6SqLXOp8BHnhX/Ac4Of+VZI=,tag:dwa6a1pL2Cxu6ZlVyzVm1Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZajRoaU1McDVaQlUyazBI
            UW92cE1tQThxdllBbVBUQ3JEbjhUc2hSWkRrCmFOeklOUlNaalg0d244T1B6dE54
            N3o4SG55ZFFiZWZqOGlqcm1md3F4SWMKLS0tIE9MdkE4VUloUE0yOVBRaHlvL2ZM
            VFprNzArVDVMOTkxYjFrWnJiTWd4Y0UKwOF0xLpEXOvHF2GumOf5mv0PDrRa2C9V
            xgsQdXIy4UKT/pREOmdGKZKa190pXzURFmVZq2e/vkpWk7l5I5wBYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-31T20:27:44Z"
    mac: ENC[AES256_GCM,data:9iAcuXloftBRHQZV3+L0vw8xHAs/l3hqhVruEF1huRv/61R1mPYBqoeDpOaxVkZQZ/JWmJv5gmpc3f0m8VnW+vRfese6w1wS25pRk7jxnt2kVTMmfUETTU6EuS7yfQDnSO90oQi+GcYHIXtE8MBCBxsCdEmKCtt04ttghB9VHZ8=,iv:r8DCrsreJlYx8ibzu7+9ghZcS5gDdhM51tN13FhJ+eY=,tag:ZFUJ0uBa3fvLjQLGf1Zg2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
