apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:nXpTsc6hCIsEZm6kevERM0RuUXVxAEfE7WcMZ1gj8/KwY/uIhl67haCRzC2QHEiBm+wD2SGImmxd1/psTgBuV140j2vuIFtcSLflI2xZuRkPHryvQp9XVZA7BK+jd+4pFaFjnR2PVBTChTpDPcqpfjtwAeMtnnbmSw==,iv:vfvd+X5KWx5d4VGqqiEPpe/SRW/HroZNsFvFuvrD7T4=,tag:iYhfrMXDeq7ffavXGjNRKg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWHB5QThVOTQ2V3VvZVEr
            OTRXOHhSOVN3Y0poWTM0ekFsckM0ZG16WUVJCmZGZVdFWlZCOE5aMW1NcUU5Znd0
            VGxlS25yNjJzWklaZWtoeHpVQzRSZG8KLS0tIGNNbmtQUmVGcFZIK2FiQXZQTHBm
            R09UTTFTT3BCS0psRFJjTXAvY3p5Ym8KAgwRUXBSK54WoAMgvGiTgi+cYGRXa9mF
            62ZVUSBTfjgY++9UB8ChTL4ERmUWC4eoBL1g5cWI56T16/98/fjqyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T10:07:37Z"
    mac: ENC[AES256_GCM,data:NhBF7ZpvhuvWGtE188uzw9yHvFgU0l0HqUm+SuoLrKwSeX+9EL45GjySPhtkl4hQcvjZAMaBbyWRv4KEWoAs6x5V2+e6zWCmifyoJANtFbLUHzNjYl2BbDAt0ph5figi9pu2tgfJFiseYi124w/AA7gWMyq9I+Ip1MOLu8ltlCw=,iv:qk0gCDUPuPvzcMyFe4Kk8SAJ92wQz6WcnxoONbJkYZ4=,tag:B3uJ37lQJs6cB7abqJSVow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
