apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:ptgOKpu9I3/5Jnl4/KtP5rFKSZRjfWF3D5Nz2jWZANW/3ay89Nx/vx36r1U/KCfbGOks8LbQBoIaMhcrAC1ddumXhRR3JUAjG9xzSmKQyr41zdnf4FLHUCi963S1sH46UWkXRhqRooq3hU4kQx6+bm9wN8+evXbfeA==,iv:aAg5aQbLV5U/uIdWvuqpVAD3Qn44Zyin+FlDShvBlpY=,tag:aMLa4m3v4yphFnRzkuENvg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYjNlUVZBdnJZYkczSE1m
            K2ZZOEVoVEtFbjcvbkh4cHV2TUt6ejBJbVRnClVVUWxOa05QY0dpbXBPalZXVGRh
            ZjJqTWdtOFRweDhlVExIalE4OGVIN2cKLS0tIGk3dGpWc2NaQko1RjNUMzIwL0Ix
            Umh2WnJmK2FrSTc1cGFIeisxSmRzcE0KsI9hqQAaTrFYFbCmqmq7EuBH8MrdnOOw
            h3l0gu3AKzieNF2x4fK+YnQ2L+40T3TU7GaU+IFc1whaRYc141FJyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T12:09:21Z"
    mac: ENC[AES256_GCM,data:By2JQwiKHjQizRqqa9wQXrNVoO+Xqzyo9nbo9ijCd5d/JW+1l9yh7xDCF3NSQf6fTVKvYgI57V4KG8lxkRXTQOnz3DIQyxtTo+stOC6C+cHSjSHJ6YgakJPrvTdiWqwHDcWwOWuVoUyXUA0YUSj4wavydgc/PgsnnxLFSevngJw=,iv:2xNFHd4tYP73+M1tSTUHzc2I5ZEwdwNkwq6vao/b6K4=,tag:L6zXXoDOejDNY/vs4/frwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
