apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:NHN/h+uEkEvfky/CRLznmgsgdbgROjBdu3SPPF8conveoQ3fjtchXQzE16uqmrn+RhizjGqGuWpg9noHA5X5AAFplc7zWZFzCyiGI/4TtoG/pNR0l74+f511GW6f9HyoIb2WO/dm0qMX8X3X8FOn8TVRbWP5vpFeSg==,iv:7dJ1eHExrLL4QVNmSuiQetqaro86rMH/7YGANYUMJdQ=,tag:TwprLJDsYxHpFZUmxqP2dQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRVlmb1pTdzZhNlJjL0tT
            TjgwVFZjSUYvd3cwTlp5NWdXMnd2eHFYb0F3Cjh5ZU5zL3VnN1JjRHRMMjN2emM2
            UEV2NjZTNGE1OVRHMDRyZE95YWQ1VWcKLS0tIFBtTG5TTmdEYm40RExYMHpucjBO
            NDg0dEJ1b0xyZ242NEQzUklPNk00YlUKYNS0RhzaZXLb5NU2E6QoYrNtCGGfaEaF
            ac+93CAQ82fVj4qO4PuNCeazp+cXKrZxjD+oxYjVEEZ1/iuBYxL/UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T17:08:25Z"
    mac: ENC[AES256_GCM,data:Shg1d899T7g45r1nXjS0EJcN1XahuFZAsM9NjNOcG4aLqtKUlzLfYXLkOVUVOvTM6i8vFxpngItUHpbQvyNQEl1QT6lUpPGXm8Pcsq04HejZuQ6rOWtUGhS/qUh8wg9zofD1/jlufttBUIBOSVWEk2LZjnc0tRVpa6AClE5ZY/E=,iv:JQy8H42/vZ8paFavLHptY67BbF3VlnMXbombtEvOdyY=,tag:muEs075OJHfonSZHDRC9jQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
