apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:VEER1DmPveoHS8d3ePIzl13bn740ePug2oyIDUluWgSlKMS43zVtJmY8nlPfp7OFPgBRZS6tRR2K+jXqFFJAaeHQjmWgby0tRbHdhxf71jD6ICBmC2PecxwUwbWAKDVChX8sO7AVf6m33HYBX5tyGWg//sFXkueH/Q==,iv:LFzb9nRWcLM1Gi8A3hd5fWwvsKV87QpEMsMKfqhdWwM=,tag:yzO66Xg/QwJyiREiuCFlXQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQ2FzcVMxVm40UFBtckRk
            MWdNTGhraE1YRm1ZRHhvNkVqSi9XQ1NFeERjClU0Szc4UTZvWk1hYk1BZHU2Vy8r
            ek50NzdHOXZUTkRuQVl0b2VEY1hhYUkKLS0tIGVJYUFjOWg1K1NGOGsyYklZNklI
            Y3R6NWQ3T2doS3BLSlc2VWN6NjI0em8KhdOai/t0HqX2O3eqQCtik5ndiMV/vp+i
            n9VfW/x5q/9x36UIgbiNGv5iqgA+ZPq1WSkdRzcLDDHOOWgyUusWJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T10:25:36Z"
    mac: ENC[AES256_GCM,data:Y+o8AYVdt5Po993HyAaErCcQbk5dlklJ6lqWfyVOLxZScpwjhOvI7FLkseUn+KoyVqN3BJcN4Ifroy5pNUaar07oelKM10sZjOL7w5fBgCpOc5Qn0l+j+8Lqnk7beaZ4FHNs41CsbES6oGhjyv9oSEqBTozHi+0ZLRCMdm3UjA0=,iv:pdWuMiijITXVnPta+XeUqSJnENLpB9gJfoxh99aEk8Q=,tag:ToF22e1SEo2rSiTswUYIeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
