apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:xyQ7XlJ+VnVK5tIcWg52KyBBPTlUs6SjEA/yrtUTIJhhSExaAXYPJVBZvEH1rt4JrFSkb8I0NbJgAEtLyOmTQCo2BUY0FqZNzN2nqQp5z4hXLkNCeB342afL0h+G8+SsOLQJqn//yX1K7dRkmVYXA6AFlnPu/SL0ug==,iv:UivPaENmYbvDhtbiUWkwZTBJ7/72z62Mu52ULToGnz8=,tag:y8uVEboDAq1vxDMdbG/lxg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcVhsQnkvYnNyVHpOWS8w
            a0tKdFJMOTlVbFZvcnZWVXE4aStablRpR0QwCjlpUzl3S1ozOW05ekRXdUc0VE0w
            amNwVWtXQjN0ZWNxS1FDK01WdVI5Wk0KLS0tIGtKbkUyb3ltMzVBSXJFM1oyczdG
            NjJSalRyalE5TEgwdURUeVIvWmYxeGMKwN7IfyPp0q/LK5rheMJpCyoixaqcBsGw
            ShQgwdzR3SmOCTK7uAK7ZdjFalqMTjCeTCWLIlLRG3WmELHQzjBD7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T11:49:21Z"
    mac: ENC[AES256_GCM,data:0jMfndPuMJ/RWPqMp2v7k5YdzHigKH4SFdokhc+NkTDsddybOjQTBfflcSylGQv8T9NawLwISvqXDdKj3wYESP1c9i/PY3adx/uACLrf+KsPmUitPkr8V2I2xnSKyFNiH6GAm6dPea0syh0BL52rMTMv32o5b+/GnAUjBwH7NM4=,iv:Hx8VhfNfrsP2S/a4uAMDAilFLjI5514UrubZat4NLDk=,tag:TaErfbOnZH5h1PHZr1wkNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
