apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:Jf1WlKzNBs+78ZIKgQpwC1hmgF76fcu1T8SRpWr5EnwGRd/dpUBzkmwdgQiaRFdhepfUmIgZCBwmJRLRO7CWxMUqgjGJiAwsc6TFo6VJUY1nYndOxAd6egiEGts2VTa4fR1I98OcG6h8qwA1DSYXPEddcxlfk8+RxA==,iv:iOXMgwurzUYXB8zkX9Xnztvb3ohrWHgWFl4L8zJwca0=,tag:DwcAPhJpffn1lTTljm+dOQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TmNTcjF2Yy9USE5HVnJZ
            N0ZvcG4xREJTTW95d21xWm9VTG1Yb2pwdFdZClNMOXBLb0Vyd2lyZTFwU1ZuZzJC
            eFV3Szl0YWVlNmhPai9TSHd1TFRJdmcKLS0tIFY3eUMxcVpDRWptQVBMZDBDV2Z0
            azVJeEpKQ2RGcGhUVEMvVSt3MUYraTQK5CvumgVo8ItUtcqYecjwpXNvn592aMdF
            wggUiroLC7IZJ483J36Ccuo4cRbN+hLYiNArKh0/xIEZAokJlJofQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-31T20:11:44Z"
    mac: ENC[AES256_GCM,data:2vkIHzOtD6B/u0yAPmuD65vkVp7e2a092+cjggQUImglKr7aTzAFUP5DMVGvsUPB+sXB4P90Xxfe722Kpx1lMKbkeUAvyea2NyipcJzI851VIm2JEn67+ZcRkRuWdZwRMDnuXLBk5HVpdlf1nArGQUNXbedDVhtnV7GOMLWrqA0=,iv:MuzLsEuJKN8LY3UPYm1RSJEUkHRDPAvOB/B2C1wrc9I=,tag:j28vw+AwBTcj7s5FMsU+pA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
