apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:0PqGrUNv7Ck/4ssoEZ/NJJjIVv+BiMTJukF+KZKz5gnuIvyXJq/yMaVHFY8jqYZU4Gmfk4C/ytGZTDbGJssb4YWPU3opCHVB86ZCLP0DTTE7TKWtdbnZwImU43j6k6dlarOT2SaCdZVhYpzEIFhrOOG4dd7Jt1uzgA==,iv:olnw0f322p7tysT1HWBhmqoUEk/wxt53+2Dymvv+4zw=,tag:P2B8qhdgiwCi6HStn1SKag==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0M2lQK1lramltSkg2aFRi
            K0FYNlEzMFhOYkk4d2VaMFlSSm1SSkJWT0ZnCjQzWWFySFd0WHZBSHdjSEtROU5k
            czNXRDY0dW50Q1RncjJxS0MzQlc4MDQKLS0tIG5UOFBqNENQd3lidXR6QkNOVUtz
            UjlTRnRiZklWbW80NGNYQ3dlUzdzNzAKW+PgSGhTyQJtrHdUq5AIoGbmuIfZ6eC5
            qIjVvJJREjxV46V5MDcyKaxxDXd0WfkZV2u+s9R64xi/ipZvzRepDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T09:32:12Z"
    mac: ENC[AES256_GCM,data:NT9tQ8xHItxcvgt0onH5R+z6jW3nQ7hOovd+OtuOe8d2LT7ignkALBaydsb1Ge2BujvlTpBXV+SwDxqTzJ5O/ViYcDgC07FSm7QfxUo6VFPQW8FVEY9qiGpZH+/K/3mzTiFn64eXYWLgF6oltK2HLmCSA3DbeP4BlV4LYa1snPY=,iv:t4lNOmGT+nGDgTp7JLAuB/pWYqQ1p837BNoVZWDC3aA=,tag:PZa9JN4di0HVeyULiayHvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
