apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:EHjhBqlKv0C3xZtWH68wEsXHBxLBjPknbCPPurrgl7/wl+fCWvX/1trmxFtnRLnFoWL6wCUkKbQ2zKt/TjOKaKJqFn4vCzCVM+lAn3A1Pg5PPmqnWnyzudkMX1raQP8SzfMX9zJ4VPcikt4Z8GWPWNokbCjb1/Gchw==,iv:c5mikgPhPQLXB6VIeddLUvF1evxa+WHR2Fm5k0ahl7c=,tag:na6lcx8yLP+BUXyhq2JuQg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubGJ1d0NqVDlYalpQYlFI
            eVFaRS9UZm5WY3lSZUVMYkJ5bkdBTUpPWkZBCjk0a2hiM1JidkZTcWp3M0pOaU12
            TzBtclVGQ2ZFcnFFR3Q2aC9kbUt6QWcKLS0tIHlYSE52V0p2clAxcWhRaG5TMEVl
            K2E5bWxGenhKb2Y1ZzZtTkZSejAzM2MKkztp83LZ6pDTDtEhxF4peCkzJ3SVrCFn
            +1Aljt0s0N3fDK8uQeb560q9Nq0f139VbXh1RFuVM1MLHJwksRBy8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-15T19:21:52Z"
    mac: ENC[AES256_GCM,data:CYSJDW4FnGTS3a6EvUzYqhGZk+tqvdoIAnVPqA3cq4KwlCHF6TalMs/4RWti6R4RSIKuMrV8PhNIHTd/6JM3BCBRGliAcn5FZ4Vj9kmzJfdjlOOPUwZVt2Xb+xItfDHyVvbutvN5cyvGs+XIcgQ3YENYi/c7elh2XmO/H+dwTx4=,iv:oPPdBqub2ZMuXVVRFT16vyNx5GU8elVRXe9s+DKM1M8=,tag:Mdu8RE6ZlZmvTeJNnEJ2zg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
