apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: prometheus-operator
    namespace: prometheus-operator
spec:
    interval: 5m
    chart:
        spec:

            chart: kube-prometheus-stack
            version: 69.8.0
            sourceRef:
                kind: HelmRepository
                name: prometheus-community
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values: