---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 15m
  chart:
    spec:
      chart: docker-registry
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: twuni
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: docker.io/library/registry
      tag: 2.8.3
    persistence:
      enabled: true
      size: 100Gi
    configData:
      compatibility:
        schema1:
          enabled: true
    proxy:
      enabled: true
      remoteurl: https://registry-1.docker.io
      username: ${DOCKERHUB_USER}
      password: ${DOCKERHUB_PASSWORD}
    service:
      type: LoadBalancer
      port: 5000
      annotations: 
        "metallb.universe.tf/loadBalancerIPs": ${DOCKERMIRROR_IP}
    ingress:
      enabled: true
      className: ""
      path: /
      # Used to create an Ingress record.
      hosts:
        - dockerhub.${DOMAIN_0}
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        cert-manager.io/private-key-rotation-policy: Always
      labels: {}
      tls:
        - hosts:
            - dockerhub.${DOMAIN_0}
          secretName: dockerhub-tls-0
