apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MINIO_NFS_PATH: ENC[AES256_GCM,data:TE0IDcgSAQz1SXGwwzgGOw==,iv:vdA64wJYr3zJx1k4JX+4fK8UnCxFyXhKp5U09YO0Cpc=,tag:vFbcHfK554/1nDVplyX3ow==,type:str]
    TEST2: ENC[AES256_GCM,data:+kA93Q==,iv:AJcDdsLElK2NyyxC5QTzEiyHFDh/MsgSbEjBYmD39fI=,tag:IFu/lwMLiVnRLJPHmhaH5Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZGM3eWNhYnJiRCtwc3NN
            MnJkVWdiZE1aZEliQzhjOGtuamdSMFVRS2dJCllGVmJBRkpXZ2FWQTJWK29XMmtP
            SXhCdG1QSllnc2hOR3VxdTJiZjc1bm8KLS0tIG9ZWUtwZTVYLzNjWk1SQkVkYWts
            UUt1VWxWSlpmcldDSjZzREp2WElYczgKf1m3coiOBwZ+SSkKzcOGlyYYvgwxV7UX
            O2472isxTwXQlkiHKBxsYAnVYTmN5sXcnuT57V+DcQ9j5Ea4TAv+VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T18:23:59Z"
    mac: ENC[AES256_GCM,data:wQ9FMVDqZuXJENqqyot4+nK463d2QTSgX6CmTLdcO+HsTcIxK6VURr2auC8dXk5NKXJywgHlUaKJZ2qBaS6UkQKDbhrSg7285OgppD6ILbIsepbM1YGDK02TN+Y06jO8ouO2wVXMor55CcZy5kkHWEnoiHtq5A8QUZZo5Y7SQ90=,iv:g9yCwstxLG/hYomYfZylTgW8Yxh5dIAbmHUPMI/1zZ0=,tag:NFarbHDi1MArG843fvlICA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
