apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MINIO_NFS_PATH: ENC[AES256_GCM,data:AdGpa/zaH3G9EmlJPSnDvg==,iv:wsNh1PV/lZh+Cnfv2iiFs1P0UDowvMh9nPfeb5q+Q9Y=,tag:ayC8m1lGqZvRyP9L2cV3wg==,type:str]
    TEST2: ENC[AES256_GCM,data:0L8xow==,iv:mRq+6z9vWF+wOSffXEv8v2ckYI9odlVm9w/j1Z9302o=,tag:0Hxz61T5WDYPrcytEh5jow==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRE1nL0RBSG93NE9kUDZY
            d00vMjZzc2xJRVozaUZhdk1DLzVwdHBrUUMwCjhEdDhCcys0YzFZZVFpN2MwZUV6
            U2Z5OHdBQVlYMUFsQmdKWXNRK002RzQKLS0tIEQrMm5KTzNUUnNTQXFycjFGMFFj
            aGRlNzlGQmkvam92MmpoZVNHZ1R2NlUKlSIhEi6PndunrJaQQjo3CViFqaZ+KedK
            h5wUXX5t+KSW2Hy1k7SDFZheaU6rEN686M6iTY6/reCmTlsEbFbFcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-15T19:23:15Z"
    mac: ENC[AES256_GCM,data:ZBALKrXNE7k1yZhfMxJRl1Dby3e++P2AXVL7HMauqHrKYL2sVhEPcEmmRrNczFMraEWkpBtmWJ13ymXMVfvaAxQ4ZmnSk0D0uo4zhjTHryXUm9flV7uTCaeEUFtjqnON7Vuc0oUn7Ydv/zZSJ4HkfaIBQUkfqDRg06Vp0/uPoVg=,iv:VUGqQrmak4LR1krqObEh9knHFnBDdiXdnwG6G4lWXG8=,tag:t32H08oXsfOz0bdPDeW5jw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
