apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MINIO_NFS_PATH: ENC[AES256_GCM,data:+hWrLmTkUHZN4thcXf0xug==,iv:7/3cOjMBeYaDzvpCD0U/lh0j3Zi4OaRIYWQcs/8tV8k=,tag:V5QGeqoqWjvmfOioDKyiRg==,type:str]
    TEST2: ENC[AES256_GCM,data:bKgxcg==,iv:hV/g39R6Rks9keOz0U8P2nazbwkja0Z1FUeCh4sUxAU=,tag:+tQpF95xZyCp+m2YsFIMhQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQkphNm5WV2xYSWNhNkZW
            WmlPOFFTcVo1L0V0eXFrN2prNDFIOE1QOGpjCk9KcWhNUkpuLzQyNW1HTGIvckoz
            Q0kwMm5mZjdxRGRYRjJaVnRRbTI1eTQKLS0tIHBBd0JuWi9wY0V2OHMvNjR0b3N3
            ME8xNVgrL1FXYVhDN2thb291K0ZUck0K4V8z3bqp0z7xE1v8TzzP9RxbXcpyeWdd
            kAJjvdXhWRqY3+1pF/7pxOen4mhLUkCM0qfK1IrT6MdFJ4PrhzeocA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T09:38:21Z"
    mac: ENC[AES256_GCM,data:mJBylNguClK5GyfMqveYfTM3RYaf+eeqEhlg5FswdiSjw3Z82oqckI6e9nAjnxxpRHkMJNJgRtRWf7Yhrk5ZvP477mhnUWSAud9lH3I1f35FobZPaX1KCHukS+oNXlDO08yZQ9ZcOWW6CFtjjiSIaKysAMumUobayz4gq1UIS8c=,iv:PMQFxwZZhhftb8YmppXgGxfKhAZVx787e++6FgFcbvQ=,tag:Ly+YBj4Jj/WkibadW1Az4w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
