apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MINIO_NFS_PATH: ENC[AES256_GCM,data:9FBJnQqkjUCbPF3uk56GAw==,iv:xrR2afggIk1z2uHoiFropSRoxO3JzT00WnfZJkwszIQ=,tag:vzoTb6b3pb4/ciujTOHO8A==,type:str]
    TEST2: ENC[AES256_GCM,data:I8BNPQ==,iv:T5H93Kp3hu8OnG7Cqxtr5rhK0gSSNCGSaUyWFdDQBjM=,tag:L4e09jKJBJIStzT8yvaGeg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMS3ArbUZFM01teHo5SXE1
            QTJMTnpEb1hDRngzaGZWeGhGdzMxbFRSL0ZJCnhqeWdET2VDU3lOT2tlbWpkNy9S
            bDlINE41L01HS3ZPeEVuY1FidUNxck0KLS0tIHlTempYVG5EbjNCbCtnZHQ2Wlhy
            Z3FHUTBGa2Q0anJ6SVNnYmc3aUpJd1UKx6q6xFp+lQzpLtgmgipj1sczxNqgyW8s
            MfgaamRrVA5n1a/XbEIX4dPgoBeIFF9GpoezPMF/kOdkF6qHk3VChg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T14:58:20Z"
    mac: ENC[AES256_GCM,data:h+IlcUv6N4mCrIHv9HxabCFGL3RbPrkOkTc1dNvTtfDi6NUXuvrRdbJFeIywDELNXprfXaTrvQTyPzH5KjBLPb0YcL6yE+bCZ/Q34R/LT1QIyc29hcDPiCHRFUtdUch1AaFz7C3A3uVMd2nr6wL9nCDx8SxvoURhRwXozvybEuA=,iv:bEorogffUi+aFlpbnXi5fuKcIZJXn8HUotl2s4N6uQ8=,tag:++dRqqeloj7/Pv37Ohd+cg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
