apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MINIO_NFS_PATH: ENC[AES256_GCM,data:8UIE2lQTZR5KDxaR345ang==,iv:u0Flk/wgyl6cuJp+NqqDKOeQDYQLecNpXHxNiCVqkuU=,tag:bnnSI5HfSqbpP66w47ylPQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:KHRFvg==,iv:0E2zo5okwa2fJVpzxn10cT+X5T9ZsLRHkscLTKJU0To=,tag:WB5/tqbAE3mwK5m358pwWQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybTk5RWRRQUxiSTVHZWFD
            bDV5dzZvSWF6Q3ZrT1I1b0FuUmNTS3VEREdBCjIwZ3R0c1k0cXJuMmxpOVo5OGRG
            RCtBYUlmdzJsN3c0cVhlVjA4MDlaSmcKLS0tIEV5R1R3MVNrRExIbGdMeDBUWlVZ
            bTNFdUtXQmlaOXh0VU40cUNWcGlMYjQKye7bFm8u2LXJ4NFBP+pcrT2RSonFlDSu
            /9enZTuOWnV0qmoYg9iT4WKtIQFx2AYWTanPy8EkiAA3vVg8YWCHFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T16:56:54Z"
    mac: ENC[AES256_GCM,data:v6uV1lEfa2i/eu4DehXng7aWmO3CUyKxuHYiN/iQxe+BmynZccIaaJHEl2GGRenxz8N2OJTcF2UHLD3NUxjX95UDi7kACkpGI6MRSRsGC5jScNsDEvLsxgBI+2gyGkil7p7qAuDYB4r1QFF2KGog+8/+cIW5WzhvPSgzR/AFd2Q=,iv:gwc7UJ/Q7wm6+C85d8n2hsb/YplMyGS2L8gAq9tg0ms=,tag:r1WBck5mnBBKhGwBk93Xmg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
