apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MINIO_NFS_PATH: ENC[AES256_GCM,data:20k7YsYIP3hTBfMu/Bk8oA==,iv:+dd3FG1hiaxawOgiSkbSJ2Cd/tL3b+G08W3y29iWV7I=,tag:CYoJYME5UNPYp20GJdKL0Q==,type:str]
    TEST2: ENC[AES256_GCM,data:ahl2Xg==,iv:bR6fWy3uwoQM3ONQWXDoLO62igVKcxECIYSVwI0Kzfc=,tag:uZGNwIngWcn8Ddz1qmFexg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaWR0dmw5eHZNTnVtS3h0
            SFBUdGNGOW9tZU5vZTZkQ2tZalhyL2RxQkJJCmpXK053cC83N1BpK29iY0pHRkpk
            dllVZWNRN3FjUlhFTlk2VSsxTFJJa28KLS0tIHJhclIxcE9PaUtLUlV0SmdIYkZP
            dERnUXZXb2xWOUM0Nm9GVmtaQjcySGMKAzbhzYaeL/5J1ngt3QKiOatcO+ylNsOa
            JLiXk0PJGMBa4QhJJws19GPyeh/j4K/vEBqP5TA+1HcI3E91xNW4vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-07T16:15:30Z"
    mac: ENC[AES256_GCM,data:jBb+mhVYlXYwO4GMYKAxcyzzCwnHtO01Y4L8L/nC8JHxcEmswZNau1bJEFWN/nGpar/RooFEEz0QtD6zCYZ0neEylRrJfbGDFlDRAXtBapbbknKRuuBMXBpjVVbab/CHmR1UGk65kWOEis8CizAlwPe41q4ok0Ini8JkMdnSygk=,iv:0HVGiB9zYeQ8iRiBHWJD2iXnXGXFEmOYlKObgG/uhRs=,tag:bq509AqkrYiw6GXjWvbkow==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
