apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MINIO_NFS_PATH: ENC[AES256_GCM,data:aZMRJhj8QZ1Br21OIRWNIQ==,iv:9pd32L5NZLYG3MlOOLOm4hDeuP4bbpnJNR3SPExhuu0=,tag:sx30Pr2wtGqPqtMYYHtIRA==,type:str]
    TEST2: ENC[AES256_GCM,data:bFJ5+g==,iv:DRTFq0/71tdZGOX7tr+TNYhSritwnNO77F4dcnJyf/0=,tag:cKv7EF65pYkYuYsq0Tnv9A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUm44cXRlS1hQeldwYy9x
            VHcyUTFDQmEySDBCZHZ5TUtHcU5sNk5XUG5jCk1YNERXdnZ4bElqRTA1dFlvTENR
            Qm1rUTBQSjJvZWl2MVQxSDZYclAwUEEKLS0tIGNsL1ZybUhpMFo0YmZMOEtWdmtS
            UE53RU5QUy8yT09BRmEydTJBUjVHMEkKFhEnkgL7/yBt+PevK36w3xPcDjwtH7UK
            Vtb7cuofxvYdJd+TYmquyMfH3H0CSHoZasFug+fWG53M09Qrc44CBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T09:32:12Z"
    mac: ENC[AES256_GCM,data:SYtklPhtSjtjBAzsWTvT1dGLn1vkLN2A9x5OlHJalYb7V+4jaWQ5lUsKiLsczznLlSnVCxTWGdT0CCaCc5a6eTvnFBeSdMfR7qCAmITySyCgDpikF7yiJrihe4TeAybMgR0Eo16BsMQf1GH1atyXMN768/3NeVNi3OttZSBiNyo=,iv:+LYDlKaE+voxF25wGCcbEod1sQScZOZURCrBLfcqy1w=,tag:IAFjqszSPL56cCIJqxlcig==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
