apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MEDIA_NFS_PATH: ENC[AES256_GCM,data:DeXxMp1wQTgg6SXQEqSbZNkdv548NiQm6w==,iv:rs/qpg5IrpgwJGlqGfdCKfYhUMw9nHh62DPI93Ct9kU=,tag:cIjaRLJyJ7BGdtjitO7FFw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:KHRFvg==,iv:0E2zo5okwa2fJVpzxn10cT+X5T9ZsLRHkscLTKJU0To=,tag:WB5/tqbAE3mwK5m358pwWQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybTk5RWRRQUxiSTVHZWFD
            bDV5dzZvSWF6Q3ZrT1I1b0FuUmNTS3VEREdBCjIwZ3R0c1k0cXJuMmxpOVo5OGRG
            RCtBYUlmdzJsN3c0cVhlVjA4MDlaSmcKLS0tIEV5R1R3MVNrRExIbGdMeDBUWlVZ
            bTNFdUtXQmlaOXh0VU40cUNWcGlMYjQKye7bFm8u2LXJ4NFBP+pcrT2RSonFlDSu
            /9enZTuOWnV0qmoYg9iT4WKtIQFx2AYWTanPy8EkiAA3vVg8YWCHFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T16:55:01Z"
    mac: ENC[AES256_GCM,data:dRqIzWzuKKeDNMMwB+ZbPTy20gwkabwIWjoYavQcxOWzvyyaBv8V1kiNXI+8qwxrccswPZzK8GU9AY42aNyIjsBVbhCuDT0z2OhoWipr2MhXaOQYXjGq6RXW+dR5EJxveKX6jtTYWxjhGDNuPW50FIBD8uCwcQsPH8FvFwTrpEc=,iv:a9QvY2MKKIYsHpejl/t0eVVEU1OKUDzaH2+fOZsfvbU=,tag:ZdKutlGc5UzyWEtRUK1afA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
