apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MINIO_NFS_PATH: ENC[AES256_GCM,data:2B8OGQz4oea0Wob7XDPWKQ==,iv:kbvfE/XBmAvM7png4wiwLVAMVsVs8Fv9CJ/t5K6SH6Y=,tag:pvlVQBgbZ28BXY+xM4OylA==,type:str]
    TEST2: ENC[AES256_GCM,data:7PohSQ==,iv:cdO+0GcEt6M+iXuV6CVozU+zKY+wa5pj0UA7/r79Blw=,tag:co8fuUQyONj2DaDYvQULDQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkM0tvMHRNTjdhUFhDWmZs
            VHNmTFBsVFFIMXE1Z1l0M1pKVkx0WmJoNlc0ClBrQmhTeEdkMWtZRENQVFlrdm5j
            QjlRUkovWDNRT3kvS0VZMDFUaVpxT1EKLS0tIEJUNTRrbkNUWVFkVEhPNllWbmhp
            OG9oUFhma3JERTVSVUg3NVRsSVlmSWMKD+Fti9NC/X20zvjM7nrYFIZbzCnqYai2
            LbRiGGlF0wHGcRPed6zeInk9xPQ3vMb+7VDT7E0mLfSBUXTEsUsjZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T14:34:45Z"
    mac: ENC[AES256_GCM,data:WBwEGZGDmS8autJVt265OHgf4NzoxjeS7srH9SXtbVY5nqTA46dJntQdMzLgdJQPw26IZv9oFJa48yCSKrkDOXP3KNC+yWP/EfOO1Cse7DgosaW8DvUBWYsNm1xB59CmzbkFh2IohpV03q7ztEYa7XnmMWkyMjvkkTTZoxo2JhI=,iv:AA9jTk29BF2a5p7Zos5xs7U4FOMSwV8ycQHiK7eUfg0=,tag:t8WzIYRLa8SFtnIydTWKpQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
