apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MINIO_NFS_PATH: ENC[AES256_GCM,data:U760VEukaJRrawyDJ6GGxQ==,iv:ReTJFesoZAkEtUPpO77tmYamQq8HrreayDMhQh9UzDo=,tag:KbkbhpfMbLZIvJwMV/ENOA==,type:str]
    TEST2: ENC[AES256_GCM,data:+y3g6g==,iv:8oDkK5NGUl0WxO6X0xYKGNU0fIEos6rcglzKiNaJrLU=,tag:KOnIA6coI+NQ9Y94JyIsBQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2K016Wk9jVUxTcG5yUE9W
            bW5wN25VeXlxNUNRdkorRkpOWWd6VlZQZlZzCk9jekhmQ1Y4NHJnOGpOK2FQRXdY
            dERoczdjL21tc21oV1dxbHVBdFFka1EKLS0tIDZtYjdFT1ZsYUh5a2JPMTYzMit3
            am1MVERWM0xpRXZRVnNFOURkMEJJWHcKeHlzXIuApQX1RUJAfH+3YezdEiwLLBSl
            Xb6HNkRuqdQAA92+CRqn2K/ebiOj3UUlI7edAru8E+IC19aGoTss8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T17:10:42Z"
    mac: ENC[AES256_GCM,data:mJXF6kPbS2+ntO2F2YM62NqwiVxakc6JfDzDvj21lc3RzBLuHn02Ib9OPXpR6tn++y03vmiqiMenb6bWlhXhCmKaH7TEFmcYkmFoQ/xXwSduTs8UWW55sQ1fQRzo4md/CiDNnlBC+PIFqJNjdv+XCvYCMHkwHBmQdxwzQE4God4=,iv:T8HQSIt3tiZFVh73XuejyY8+ZI5RdjgO4mbmXy/IJJ0=,tag:uJ4IT15RMZSqKv9Oa53RFg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
