apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:luaoQGr/l7IZKMX5UFTXZsIox2cUN92P46Mxao2pfv/7a1Y8VQRCyNh5Q3xtKiAhAAWPLbxl/LapzuDqMxTQK9M=,iv:eRRYD28Gk997o8aVPneAaPTpHMi/EDN3vanS469Qg4U=,tag:T+9+3zJYgGwPVJCT1aNaOQ==,type:comment]
    #ENC[AES256_GCM,data:ihcEpQufAMF1Z0+Umi6gXfAAZxcc+2lHzqLDYnLgX08/Zpa3H2Frk2q9s3M=,iv:Qvs8Qmo4n3OA/Nl8xehg17lnX7GMH+2YoAoa+YAPqS8=,tag:ZkNJ74s1HFwg2JQ1Y40Vzw==,type:comment]
    VIP: ENC[AES256_GCM,data:Ey77bvFtVHhJc1CXe+OV,iv:YODOECJ8g4V/6D8yNcGOgIHjV+3YUeklgPotyGlUUuM=,tag:GxN8ViJd2+Wr/2BU5gah+w==,type:str]
    #ENC[AES256_GCM,data:jY1gHG35V/9JjoM5xaCKy2jJ78ldZy1d00a+,iv:uW5HXWtDvE62c10o7MYZkOgAfTHh8I8nbRY8+XawiIQ=,tag:zRlDdn8V3RN+BCrdPYhTVw==,type:comment]
    #ENC[AES256_GCM,data:8LWmwlj4SFPM/v5v6ekMLGGUzyWrUjT6jcP3japtKs7Sp3CwA35mx3adCH0tLcGD3wW517TpZ2lr2jRu14mhRyanKbtS3yutaw39pfjg/KcXHfzpeQhTTU4=,iv:vfghxWi/VztuFASR2skhVxPdM+DBIbq0nzueRHxZk+Y=,tag:fgEzJQW9TBmbYjPodrq2+Q==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:9lBWbzzoJDB4flekK9oq,iv:GIAxr2pTThUmmpXWMYg7dgnsczjEe2b0ZQB1s29Hlio=,tag:UxOk9GiQQWkEBZ0Nt6h3Kw==,type:str]
    #ENC[AES256_GCM,data:1cUm9dHqfGXPJJdoMEneJBBfsd1s0dO58wvbRqUwaG1jRg==,iv:IPGgOhveHQXyj76970LYQqnsdf4ULvnsTmFLhXtR1jA=,tag:sfLSdQMnvomP5KwR4PEM8A==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:1QW5HQiq+GYt+QZUDg==,iv:offaPCBJFzqbc6CYF54TcLgFIDTJaPxwrammSFyXy60=,tag:1GUH6liM018UR93MRKkCKw==,type:str]
    #ENC[AES256_GCM,data:qgp/5VbioC04zv73Kmlur2ys+QJEBbjD/UBPK+secy0JEyHUtS6gQvdxNTRwt98=,iv:SdmFFYE+JnEK8ewgXe3TygUfMM6IgtqNt4XQ7FuimOs=,tag:mY1d2YQONnRVX1AkyPiBIA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:O6IlO0QC1eNmYzTfxBoacW/Gp/vwQHyw5oW+n3YXqA==,iv:AwBXtNGHROmG13/ojmqLa7mABdrdNyv6/wBE7Z97WrE=,tag:xGVhR7O9vt3eUC88YT4v8A==,type:str]
    #ENC[AES256_GCM,data:V5D+xsUHIwG/fHlA1gyuZ7GxW4Pz+K8/3SZLm1lyFx9K5tb+YPHDVxw2F23vEbmFp7Qv9j+ofPlruU+z51ljMXakLHSTQGpRl7IPedX4t174/g==,iv:UJHKrrxON7HW/MeLgztdAduCh3HUhimIGsqLZtolqiU=,tag:Ov6b7zN7vc3wOMKfGyZmZQ==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:adQkIWBywDrKQWES1aEy,iv:nGxkn0HmaMlIyGyE/yuVFNQQsLytss9tNgic3UXBdPM=,tag:cyKkABEaGYM92/8JLpef9A==,type:str]
    #ENC[AES256_GCM,data:YeN0N9+ZDLoS39HoqWeuZJzG2u3dVE2lbDwod1xbJkxx,iv:Q9vdfowdfLtUOqrx0nFP0GCIJC35sv1o22sr95y9VmM=,tag:CbBpoJ09k1qSNRJvpDEdgg==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:teZ2PI5s5o9ziS8bB2FH,iv:RFJUWb+Yn3hrlIJAzfWsxCe6Z6Mq7nZB3CQK/1V6snE=,tag:Ok1O22uexVxqUBOuxjIAoA==,type:str]
    #ENC[AES256_GCM,data:7uTM9QVfN5kaX6UNcQPSqnnNKt4/3rPZuAJ3WgGPRRzC9Hmw0P75Em7FiNo7k9bLuvH4+PnMp0SeUIcUVygffzzjdI7otC/1k7Zjm6srE38=,iv:FDZqqyuVStOpPdHoKJlsaEtRa2OLgwKznbL/GtbQOoA=,tag:I0RWlfi9LFkRGxLZIjHmLg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:e8QHlMHr2yO3J7xl6esz,iv:A5G783FPKioCoZh5iQhMbPgDNmrEgI/ZigmzYgNX2hc=,tag:dREC7mmL8LCSrXosw7kdSQ==,type:str]
    #ENC[AES256_GCM,data:lkTg9kZvjktwv9p5LgcOqqE4cogD7nDZ4a4PASUBva1DPph7LwQNXqt74Tx/fpzKN2aOqkg9rOMQQdH9CScnGzj/92yUfYFapkcGvJMwTz6QlJIhiDvQ,iv:htdwOu3uOutuccTZCzYLFa6AirMB4wEtWfLha9R2ZsU=,tag:QZeMJO70e9WM177tpBp+3A==,type:comment]
    #ENC[AES256_GCM,data:1g7i4Ze5J+X0Lc+trA5fhU5RT7YCo/uzwLZFv2sVc8y9EpbdmYcHrfeive9uiCj24T1HYTcbaGMATzImzJBw0KEnNyBQahEH3OSFblnT0PA2rbrX7VTQ2WMbBpOwK2KdpNTy9Gh2ZKr24Myb7hntHss3hk5N/FUaGOCfYQ==,iv:bYKx0bB5J7DnFmqKZb4zd0x/P6IeBbMKjH+YpZ0dJhw=,tag:p6gKRkqMTQ2ixFJ9XiU0pg==,type:comment]
    #ENC[AES256_GCM,data:+3PLl/yiMeWKxaSWLcrv3aj78x/JacghZJJKEB2FI2Fm7dEjunre8PNPReOaDSM/Bo1+my4AD7d+FdEnvP9a73+D7fGzonj1IouuqWDilxk=,iv:U5dwyg5lbsh4IcnAVUNHvpevBU8SYHcJLHtxz6OiEzs=,tag:f3Rk+32Bca0uG0XXMdrwxQ==,type:comment]
    #ENC[AES256_GCM,data:OgTr+S1AAFP8s3GFEJAdW+AFZKHAbxKBzzDbnhLw3rqqTyJe7oI1hsoF+BMJc7Q3CbPtNE83,iv:WiI2rOpnQomdawBByvLGGwZdGmhH6oJCHhpO4BnOh7s=,tag:yyJkSyQeHYo0oowB8YWxmw==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:tf4oaxyF3muyCapYrZf1,iv:SBw9nvfaHYR5wU6i4sQ7kzz74P1P+qkRC2IsW/iXZ6c=,tag:/X0aQrFds9iAKgz7SKnUeQ==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:TFv37hD/VtoZ/DorgrVLenc=,iv:N9+WQVXJZUEraVvL4L66VqLLFQAdMGNEk1bg0w7I7Sc=,tag:U+gIrAAbbfo/ej8sVMv6/A==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:HEXBCDV2Z6qFqH0gxo4wGGYWmFoPSvXgoxukMf0pzqANnJ/6BnoxRA==,iv:sWHLG1NjXey+yxcTUzawR7E95ZeoMMgY5VryoW1DPBA=,tag:uozNEekzzAK+Hd2TBixLuQ==,type:str]
    #ENC[AES256_GCM,data:TRaXVRYs958aG4EXMpcUxktdwTxylK/22xtnW+yofOJp5FCMK3K07Juo7aZO3afYBL/9I1KD9ck=,iv:WIXYC4Svpqn9PPHSzTGBQ0yMb7W+VM7alHZSscNHRpA=,tag:Z7QLn4aCwPxEJRFx4WxWAg==,type:comment]
    #ENC[AES256_GCM,data:/iA62di3A3jmwb70bLV+xb2taWs32GVDjg==,iv:QyLToxAnXUtQiirBlg4oFcJN1D7afd+8mUbmo7PDmfw=,tag:Yb3vOOXTqYuceo1IShizMQ==,type:comment]
    #ENC[AES256_GCM,data:nnoL4qDVimxvWP2gh3nRH9XPNyBO0/5rRWaaPqlGABLpp1AVRJ/jwTqWAzKH3SIU8uLWgwiB8Fg0PfDd0mU9ExdUId3xD96KYX/eK+s=,iv:L95Eam/15NWZBCUKU1YznLR3jsaQTPqnk4g0iXDdZS8=,tag:y+KnHnAph9cUNl0bwWakxQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:HzYFMr/C+QN48ObABMdm7tuEL7S6b8s+CSlrJUHoXt1lgMG/RxSECkqVv9aNxg==,iv:8ej2fGt/44+yScGMD1XZUElr9hjjcM9FMs2n2B0+s1s=,tag:nfL+3JtSGS4UPC6g7LyPDw==,type:str]
    #ENC[AES256_GCM,data:aIZXlkazjLyOIj+0jgSQVTWpG2LazvN+prt7ulR6G8lmXscDbzFFNz0AL7CdEB8ftNOp4q1WkKz96fUNIUR4+Wdzp1tdcr0=,iv:T2iOanu7Osmr80cZke7TiFUDd0pBQDw8leE/3LVA2XY=,tag:0+3gZC/leZE+rm5doF5z9g==,type:comment]
    #ENC[AES256_GCM,data:fEQdfMRosXHpGLkeJmkUZyuAZsU937a6L/79AlBrAbEBcz79bR8VNqtmG3PLWJwhZbloMWjI,iv:/hKQuOOz9rZR4cTvraEqW7y1BwR4b3Gs2XjvcQfMrLE=,tag:UF7A9DrVcuD9zJ4GznjvCA==,type:comment]
    #ENC[AES256_GCM,data:rYiP3/nUng2vgk5eGTVMIf2BxZyEkwovrO+RATfbVi54f/U=,iv:45jw80uUWXg6ncUauwNfJ6/8zaOv5qtOc4X0v9iZ2XQ=,tag:994QucxHqce6Vnp3LvvpIg==,type:comment]
    #ENC[AES256_GCM,data:RUoyv61/kxkaBJBUgUnNplxa3sHHdSJH+h51WvsUWNPADlQ3/DIf,iv:PgiIhFePhwGX6IvR1Wg9M7RY2VWUJHACQwuKQTnrylU=,tag:4nRzp6jbPQWT3FOYldjXBg==,type:comment]
    #ENC[AES256_GCM,data:yF/oz1fW7UlenDpZdck=,iv:sN8+3Bo1YUFPMXnQneABuLppVm+rt7s43VrtT6sS0QY=,tag:0acBUgcllyyzYmmZxuBfAA==,type:comment]
    PODNET: ENC[AES256_GCM,data:z6EOgiiZrP7nD0P5qg==,iv:vwQxLA6MInDNMMKp2BrD50I6p01hzIAnwXieC+Pr8C0=,tag:uLvjq+KF5mdH/E6Uu46Miw==,type:str]
    SVCNET: ENC[AES256_GCM,data:tr3443kludPTKDK1TQ==,iv:z4bzmVecwSiCZQwa7g7QwFFLCjKokZMyO5BzCsW18dk=,tag:hVaMEL61b7dvuwpJupRo3A==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:rbECBQ==,iv:gV5Jt5nvhyfF1sCv8o5NR3Fq387W1VNztz7ChLSCZbI=,tag:3MSemW7OkzRo2zWti3R55Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVkZOQWNwbTVENG80SFA4
            c2RCMDNhcURCSFA5VzlzVUVTYW1JbE42cWdVCk5mRG9RVmRVSGk1Sy95Qy9GbVhS
            S1RYUUQwMVp3Y1ZUbFplaklRRjJaTVkKLS0tIGl3cjM0MnZCOGNwQzNaOStaWlBT
            T3kwQkdEVXRkRVRpZFFVeVYveUMrencKwnkW6Nf241a4IefenYQ49OU+qDGDtQ9D
            vpe1L0LbZV7C0ioh4gF7htOFNVPWzm6orEg1l16Vn/7Xo5Xa7bt/OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-25T19:47:26Z"
    mac: ENC[AES256_GCM,data:cewjgsARPtktBNWrXIyVoB4LRdFXD9hnlmVBUhLjWyWneB7w4yk0mGD+Fk0rADbL/OISPOB9Ah6C3JYHX5S2l1ukUI1GxnPepRYF8T2K7LxXK77mrkYQIcGYmHXIY2wXxImaFj8cMvPmPdTk6i1VIi/OjHylI27n0qC23LLp6PE=,iv:vQOwe6Y61QY/EYnr3cxLGCKYAVFU5byKqyiX/n5aVY0=,tag:ZWiyw747uANnGnd6nMCDLw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
