apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MINIO_NFS_PATH: ENC[AES256_GCM,data:AsgoC8ZesPSBJlRiUyIsmw==,iv:avf6nCD9IWtmUPQhneUOMplBbu4sgvXHnewZxbsPelQ=,tag:FHjDguXEnoyjRye7fzsMxQ==,type:str]
    TEST2: ENC[AES256_GCM,data:2rJ3VQ==,iv:kNKRa8EPjuU/u1ASMl5JdqBLV9CY2G5fh5273YdQkvw=,tag:ptwJgbUM4It2TX2UmrUN6w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOFhHdS9QUmdqSG1hRGwv
            bHlMMVV3cjFQa0pxL1JqNkd6aVpGTEJIMW5FCktIcEIzMi9Na2dKSTNjckttcHNw
            RWdOZVZMWDNHK3BBbXZuOCt2bzlhOEUKLS0tIE1VSU5VbUQ0RmFLZHBzeWVuSUZy
            WjdEcmJDQUhYdWdLa2hGbWRSMmZ1SlEKnic3sWYZAZUPhHZKV+cOJp/u8nGTmLu2
            HOUef1WfpG7Sm7rSt7bC+7a7mT56828fgXshFv9h2wcARL66Mjh/3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T13:49:35Z"
    mac: ENC[AES256_GCM,data:k9JlXCknIdwLG97L7nm7vJfYbBzcnPh3t8rBURPki6ND/zI+apEEkiFkAyfZcagqrkDSOaSY3dA6RBKKaLhDGztetIIH+D0a675gESKyk4b+UI5akZHRG4egWaT5zEySHcujmIV2AH+dm7x//pPzq+j05tdoNCYODMEJyFToPaw=,iv:nxO49KV/zj+UNYyYl8RgsTvkGMaRxdS9DAeWC/hjolk=,tag:XMVwZ/A32gdbhixxk88mOg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
