apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MINIO_NFS_PATH: ENC[AES256_GCM,data:flrBWYcc7tDQfceU6OAe8w==,iv:RY2nOflomG1QwIZxnAhbbNYPKP9dT8oEoqNywmVOY0g=,tag:JLFgB6O0xtbvGu2CIg5hdQ==,type:str]
    TEST2: ENC[AES256_GCM,data:Xy0HVg==,iv:oyT3fhTlB5cytp89u6JTgMfrAWxuV2r4N+z4LE2P/1U=,tag:okIKxuhpn48C8eEAST1xvQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZHVyV3hlR0w1RDkxYlRJ
            OStXMUwxWVk0QlRVSWVUTnhLaW16WVJqcUNJCmFESVdTZ0ZpMUdBZFFOTDdUQndY
            T0pXQ21odEVEeENubUpHWGkvTWxybDgKLS0tIGpKMGN4ZG1YMko3UFJYUFkwazhT
            SmswVHdwVUlIbmtyTTRyd1FDUVhHS0kKEolgFxec8ytIV/tjgWBan2vEKQl8CHrO
            P+G5QM49sDhXm6+XEH3s8JytJpAVAAeu6zJwNuST5YuL91PepyprdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-15T19:21:52Z"
    mac: ENC[AES256_GCM,data:f8j+966BLbfeakz2NNeE7SaegNXiGNl95ZIpGNQ6v7weWvC0MDCXt4x8PjjPY8Z6GtmQllXvPz0PKiFVuP75hgyrR8djYnOboaD20hlFZ8+bmuFIvfJjRKUmQ4NWbJLL+/R+eeR0+oS0Fj8TsHLzL/BSFtftb1xgS+Pb89jio7M=,iv:v7RKKcg1a9g/OXuJBoeRZlGbSLo2Bd9Rf5Nf0J3kE6I=,tag:8BgJLaJc9CBN5S2ADgDb5Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
