apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MINIO_NFS_PATH: ENC[AES256_GCM,data:ph3m1xeu2wxsaC7hNoyKtg==,iv:xDiQmJ6Sw2M5zcMjmw3T9AheEkhWBxXjWRLH18Y2fkQ=,tag:KRXrY+aEBjp8LURsH9hndg==,type:str]
    TEST2: ENC[AES256_GCM,data:phTYEw==,iv:7ijLlOFC6pzCFt5lADZcNUHS4IDkrZINIRbh9j/WOTA=,tag:vKaZwstvGHu1QDta+0viPQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TklJN3ovcVNtVjdYQkkz
            SEFKa2NiVDFEL0JTZDFpT0k5anRRWmpncjNvCi82dTEwM2JyWUhJWXJBS2V2RTZp
            cGxPY0wvNDY1Qm9nbXl6Y2gzNC8xQXMKLS0tIEMvVDQvaWhhS0N4U3IyTnV5WEJm
            bTdYVUJBU1F6RWlyVWlMTERqT2FjYmMK9vcrEuEGs3btuVatKENL9UA056pMRCDv
            UVvO/xlulYrnA8kje4CoLMg06ns21ESI73cq6PadzBgb+zx4XBCCbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-15T19:05:31Z"
    mac: ENC[AES256_GCM,data:f8NkWE/sFx9PGjtsWWMUD9NMZdj8Ns/7QOQfKi8JZm3H1qTtpxGzE+KTS+7LqYpVxkSzhW0TwmiBtgzCLV4mReLuA3CXnhbgODOb9wQLAC8fiW2eg+naN0V86JbSjrcXGhIXU7rOa5XyTvvtijGn56xeFXJq74s0NxcuLvGru34=,iv:duY4OriYJBdplHXpd4ek2HGdStcyPTwxVbrFVeJ3DeM=,tag:GX1qDx2la4Z4socgzO2Zmw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
