apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5FOPfF41lRmtSXEZ/LZJZ5aXKmfLWDw9YuyjpsemFMaktPJNeKqBGhTcY8uIjQsuvxpC0E6kYIOsL3YzPWHYESyeySvS57HOfjtlUmgMG9gX5VknOWPAJThaXs7NOQywoiLeszqcINZ0q5UCvWbr1xXo8QvhR0tDXQP14UxK7erRI7o1iLRRpgFISB0Q6hLGYfPKJq6+olaw71yEd8mJodIzqArCKGt9YXlT3ps3oWRqbdAze6bJQLyZz+IuvIBA5iKIj6qkNXv9TIl3Zj3+Kjo4WyByCh3fUXvuZDbQReqgx7MP+/IZqx4Lgr4dzgYGiNp2wfx5OTg1RYVgJNt5ZjZlJe0UckT9sf9cSdvq8INIO3v2bsUIr427xQpSqVw9,iv:fNdep8owXqa/ull6eZll/rN+i4Y4T93/LNXtI+Db2Uk=,tag:rd6yC7b9z2HcIxcTfNiRCg==,type:str]
    identity.pub: ENC[AES256_GCM,data:fz7giaJoMOaeBbjP14y9cRggrU3DRxiOqaTg1C1pzcRCgXZ8+Crvyu7wb9ijdUdbkefnumBsi2e8MG3qEZu+TG4pxA8Fxaab0ldp522t5VIC06413+A2BhwstahCs7md8o5dMWTX5cZrhUqYNLG9eXSYeMQfBASjpxDoAuqX1LxTb4yj0JCxk9hnGhshjGSR6UegkirDiR9mVT+7uICgVR8jQ+NrVKwV0GZ+UBTwm5QwVBmX0XAPj/vawsqQ6eYy2133rsUuZpSipHgBkQ==,iv:0cbTexfwp9+v/JkMaJqjvG0KS4mE6FhwiJFVbWEOZDE=,tag:FukFwnyMO7pgZMEtPjMEaQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:rWkJjP781BSTofbbqYQBn4/CSBRouS7RDyL9pkX1kgRKBUAq+Ou+kqSHf8jIlXj/LfoOQFDzkDlNjCaIeODJLpN8DhF/RqQ8dXU8Bmwj+m8BrqbqSbaI6uO7G7tHJ0eWVqjPCP+2RQ3seCcTgwyequqdqT6HaziMOiB1vlLUViO2d8p/SvjtXv7yfZrzlBYXIHHGjZEc1rLTaIgxAFBGL9qnyshbjkZuM3WJ,iv:bPevF7SRwBguH68S5prIjezpN0pkLuZQrbAy153d0lY=,tag:ZZTDfyjYP7BwYd0nRmBWWw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RFRFUGZrekUrUVQvaFF4
            NVJQM3pEaFZaK0dWdVc4bzk1VnZOL0o4NXpjCnUzYVBVemp2ajJnZVI2dXlnTytP
            MVA0OWVUbWVLWmhrQ0c5QnZ5aDVXeTQKLS0tIGQ3NGoybisxb1Q5cWRDRnJvK0s3
            MWNSUWdYMjRUVGlHbERidUNGei9aQWcKlwd2T/P2ddWaognZm6VDMSZG+zUnb4kH
            EVxuXz7gKKjuDfL9ebCyo/4tt6YIr4zOcxz3lwlyOgTwRkWSy/1mUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T10:25:36Z"
    mac: ENC[AES256_GCM,data:Q0y2PMPuepAYa3rBNVj5jzsASD5dScpvjc0wNfd/NGbzqIKSHZZa95bTsmnbXaAEurq450rH0ObtDhCxqcBdb3l05abctdjkpQFMcML2OELaWMYNnj+joRCMq+JtF939x/9jTLdugTnnW1pxfJoCZpAmJ7VKSerUSRngiKASjdo=,iv:Vd+mOx7CfcQtnlWLjR9xSrOKPZYRRZ5oiVRJunipqqE=,tag:/AmD/zGP+1WCr6kFfWHlaw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
