apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nxCqOv4KyIDAKry4VBwHq5ia7YIppkHkre60+kS0iXGtnJdNxEkdCqawoVak2lhhxWrByTYwZhkmW6hQfhFt0G0LV6mQiatq7TQTMJ1zCca2NqdwrjcR/QK2uqzL2ZgJafrKL1aCIw5R8i8hsL5SkVbaiC3kVeMyazRAczm8prJkjWpxZJwnHZKsRQTIigw3uithh5iwtErEfnU5TH8aBfImv+2PdMjEd5A9fjzUXwPnZWgV0aq0OEEoj+MDAcGIkyr5aP3JmoQdQWT3yIDVPXZRYoSufLVasBjBOnhmDOV3aROXgumBOL0Ob0thI/fPwnrFOgs3ghr6CGh6Tn4SZmEmUcaLWAllBB1EcxKgSqoj9pgUyquoZsmkZh4lv5kZ,iv:w2eLVH9/RVNwTK25s416buBc1XoraPOHQKCFuIGNFuI=,tag:ZjJl1haQIQwICsh1JCKU/A==,type:str]
    identity.pub: ENC[AES256_GCM,data:i5d9WrExRBu8t5pKxC3E0oWKvPISWIITUYo74KUwN6jPGtRo18nDQvqM7iUj7jxcKdtDLUfSD5Yap9y13Up8cYFLL4UYsM0GnVb7+egPZB1dcPrkyFZdAN5wIh0I3YtjZzY1DcljjQDmrL0KqEnKQ9eZtEQsYVSqv7D6mrTjx6Jjpd7q9XDKKzBcJy8SkiJcgzWSwXtGal2Aaow9WRT3i6qF8aOmZqOb3i0EoAn2ScfaLl/CxMM9dgd/0fGo0Q3Kc0qlrtPq/KC3vg1Ixg==,iv:owNyHX8SONWEA9gwEhl0CH2u+55NCKxTUWoos4T8urw=,tag:4LgvsBE0gyU7k1k6c/oURg==,type:str]
    known_hosts: ENC[AES256_GCM,data:sXVntkaNPDj+sY20CedL84j8X97nVDEIxetRUFc5n/MZFhlbdHKOq93yES28VmAwFhN3L/8t0GAYEJ04lbYzkvvmYmBfD6vclCweGvcw7uJdlEYiJsSTi5Ui9lXrXQfCt8NBQ1/Fvy8a9hDQGZCqJJ1p2Mkyq8RDIl4dO4zqVLXHiB4w4YNWhGPXsUz62RxYHlaRBgH9irhf4S6FxranK1vU6D7Sl6LT4rVW,iv:mCIDzSKPbK5IXsvV3U5JfVhStC830SVj7+YHEbilhz0=,tag:lsJXRM8Fr/8jWJ+SmS7aZw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVHNqV3pBL2ZFUHhMbWJW
            eGcvaktUYkUyaENtZEhaSE04NFJoQmxFdVg0CkhKSXgyQ0NKTklFUTg0eHRPQ0dy
            K3RTb2huV01WQjB4SjFWTmRrbldRQ1kKLS0tIFpPL1EyWnkwRlJoalliakNYRllp
            U1V3VUFYWDdkdm5pUFU4cGhLbW1tdUUKYlx9XyKzFITJwv9vbTiK5Ua2NtFEiNBX
            UJMXy7rOC/Tq50aJt+IAKaf/rs9YaEQPMrR3mZgFh7F195tNLNOdUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T14:58:20Z"
    mac: ENC[AES256_GCM,data:KFjCMuHgpkU2HUxXR+EcPOjWHrD+4PzB18nFyY+3pS6OTnL38+8lLzB2nofenFkvZHotbPt+LCkpjUGg1cpTWIPql/0OXjR+mnpwwGNJC6s5ic3pRCILNN/SB7ybKuowJh09ldbsceNAsBnMmb7t/JLZCGuBVbgr54gIUt9EWoU=,iv:wYK/gPyaG3seBG87yhAUNt/eAWSP1cckts38xF2g7QY=,tag:Cp5lbcag0YGDppUBoEsX4A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
