apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3ZDAoxtnM6dtj/aK1iIqLOFge41uJVeyhJ7aWUBSbDo0XSslu1wdkuMu9U08UgHgwYvbcNw22gw/2p0tobqVPSDK3kQ/7l478b8XH24jB8oh272JnCv5NXOpqnlblIApQQIioCwfKpUwsl1/f+ioHeGW7w1NWfeKhut3zw9brysQeSzplGNnLChvgC9BM5XBA1opXd2BDgQx/gHxAhDsaxKa7ePEzAY6EaQPCt/Wy8O++N18eGWvd6QqDttQewa9MCiCorbnchI8w6b65IM7itFt3VMtOuIefPJbet21DEqH2QVo8VSFmoPkiqvi6Ixih0dqp50GPDF+z2AFcekYbphz5CZto65lx+Gxq8VWd6dEwKbU5pQJ8CqHk254F75Q,iv:2h/4817Zsowxy+QZ6p66YHl3TFF+ee8SiPAwaUY+DbQ=,tag:kYP4+jrjVQHcr17Od8UUyg==,type:str]
    identity.pub: ENC[AES256_GCM,data:EbGWmKmtST5YcW0c+xh5/zPV3vAlaWx3EH5kbKUF1zcSwjT1+h0qraGKYTTUcs+Ix8SndgHg+N5I2M5xoQNpFvqJyPYMmwVYFminC0vLgwtm/xAUpkBEJsnTFsqlup14V7C/xjSAPyzdr8wTgNuAxjVp2Aty5DqUmKit8qWyEf3GQm3rjaR4LnNDh/TB8Qk3/admacpFQJVN7cXwpMNT5OAksyvW3iVAItgYHPKZjrQGw2Hb6n/5Fh0c8h3VQu0NI5Bto4fxF2Hi2TUQ/g==,iv:xId5H/stOfK68HRpzejbvc/TBTd04MCbVLZhknVv7uU=,tag:MBcVJDy6DdjRcdEgpkIQiA==,type:str]
    known_hosts: ENC[AES256_GCM,data:dih5W3VPhN2k7vw4luXUjvUGjhNvuZydOQD1lY1X4NiDmTUVAnyHE06aAzcq2Xi9QQpW31bNhyB5F33mw8iEie0YYjXmJS6KiFZyA3bBtvTsTM6qZqq7gxDLh39aZsAWscZ6z6jqr6eyINvrVdMh+OSUls5yq/xDK8VVR4GlvYUl3qdkFuPiuvt0ajdcphacK23b5i93yqJOlmXhNe1mr5AfuKFMNqFNjBEB,iv:t2Hpl0G+nrOk4zuW5qZm8Uqny6JmWmhLwzdZEpUvfmo=,tag:Y8XIlq5Ke7q5RIpnsPxHtA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bUtDYS9LM3FrQitYbGhZ
            VXBvNE83d0xFU001Ukl3Y2Z6Z3p0OFRBNVVJCldxbGt2VTF1dytWdERMMVBoK2w0
            ZmQ2UWNrcUtRS3AyV3hMSVAwR2ozRk0KLS0tIFlDTTNrK1NsOGNtWHdaZlNqWjMr
            VzlrbnVVVXhWMkJUQkdTYjVsL3NyQW8KoCz+k37WddBr63uNIVfQmge/7sIopjXb
            EILBmMMdl50C0S3NutQrBA4jxWELRzKwy4NxdivcR1hKnsk0mPo7Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T17:08:25Z"
    mac: ENC[AES256_GCM,data:v+5AeawQCxvbAQscZFpQ2/cfvXF9hp85/jbYo/V7efID+zhIvOWLKiw1sG39G8En/W4/3ZdLQRFoRNfkO/NkC3boDhEBl55B79neaujQWSgzr663z3qhW9j3YDLEyw4rSKeasbua7oiYOvl+nTldxmL2fiUuv+HCSwp3DYYxqOQ=,iv:k/ISnQE7iGwmZW7resrV/9lRHs07/MGvGfN6tZcLm68=,tag:Egj/Bzyu9PYPtFb7pP2q5g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
