apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:euy5d3jVd5cRk1C+nPCg+kFh4D1tVkYTQReAp9Xtk0z3eahm9KjEKyQJXPNRfYiX7HanMg+hCTe4Po1uBvJNNzgLMdO2lejt6vNlBIlAhCz8bpAEjMaNmpwNR5BcrpkE2xHUMXnNvrHG32aQRzZDme1gmsvoNuMMOROqETcqkbOyuh7/AFNt9K8DZtRc+Pr7q4d9v9o0uelApXSmOtcWqB8bx3eIG2hSheY1wnUawV2VJQB7Q7AUlThC/cWVjJ/tL6dLPGde2t+5MegvkC3dmmQigMX94CYm+7eUW2YieigbyUhZobDgCZWSExa78bETvtY2WFlYyuN1Y8u1atPz2a+7MfTiCgPC2cjoig2lr5j77uoNi5irOfuuAS8dPTlc,iv:/hBdScpd6YlpMaKutZOAYmMqN905MKJ8swg8ZXhxWLc=,tag:F65YuYHOnIHByGB7rsGpRQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:JGqB3zfGUF1XT9pVlwEETST3MfAgb+6k53IyW/GQkNxcqy7rkOHByQBiIZzOu7ez6uWIdK4ZpCtDymuZJoOE4rX2K/pMR/0C5UB4UqzT8nRMUG+OGJ5Hp/VS1QdjLYkXzrxPvaYPbm80wU8QaOwK36gCU3eb+nRmv/7TfODS3/N6J5vPEHBs5bhJuoqojsv/iZmRAlZloY0PEs5KZYOGe8JbVdzoQMR4t7iNN6vJi+uDhiY6Pu/zSngGWcGFpcHrSWc+51QZ6D73fj1Juw==,iv:k0BDlBHeS95WWH91v+U6x2X5JgXUROjYcigTsr4UlFk=,tag:HN0SZuzCMloL27X1TcPmvQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:hrQ9Rcv6xZ0qF2WPTUS24dBteZoSbJZZ1NbfgG/G6B1MKoTejgdtX1yV9oTMFTl3Np8/HJCoOGXHXadRlxRK9FJyVECyG45hPhXD1PjcIVo0jiWFjiHLUvDkzgy1X/OBbD1MA2c6xRL6hyxViDuN3OqIq+VsSt5HOCFJyCoMM4lYGB8owQnEVex0yWodY916NAhksBO9xt5jGN+ywxb95tLoFhB/J4zatmWe,iv:pqK+OHeeSxZ+CKRsa495GQn2Z8ODVHEHUTWGvP9uhHM=,tag:mpRmwpDPpNXLIu8yoc6HgA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuc3gySUNCc2JIcXVEUlhu
            L0FnQmFkdGJpd0puUmY3OHcrdkNmNC9NZEJVCjVnT0hybW4vSXFBK3U2N0ZNbVBi
            S1VsbkZtUFNGZFRqMFRlaDFVVjdpUUkKLS0tIE9jTHEzT1RYbnlCQ1E4N1VQSWVu
            YnZNbVVzNnBpQzVOZFhzcUg2Z2trV2sKPODGLq+xzLVKp9Xoh9/+B4ZtNQKD6Lp2
            DrjIeJgiL55Klk5tdrtNt/Erv49/0P+6KA98ei8XI2CKi3bja0fOFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T17:06:55Z"
    mac: ENC[AES256_GCM,data:Je62rsW9gwMPmCFWpjMNodGR5pBJ5dCXJlbMl+FAzJcxmM14PHR0BSuikHtjq/8VG1BDeL1qF09FhojBdwT4fnmLXsijpa7yTOS3yhYAxMkRUIo+V/bSx8WLtYlLHiLCPUz/woGCUAOCM9R2DuKCc18M/OQ662TYZ0SyxdnPwTI=,iv:8mkHp9UrRUDCdbddzrvt2UFg9k+Rz0OhETJsgvoJF3s=,tag:GNzHlh/2icHobQprhn48xQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
