apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:kmRMRmbL2NO6oNqT2OdqV21SeOpkKHXoFb9OikE5hco/KvalzajM179hw9uwS2pe7QsT1MliMfNFsLvVuXWMjMW37PdTVVZotVSdknSyoGvE0BmFqXOibZagjoM/qoDCv/3j6EgmCiYOfYjrfWSC1M68P4MJGUmeCQE3vO2OF6L/rLCJFAphNf0dpTlQRoN6GtxGdPChpYsVO3Fzc4b/gW2iPOWyfkpicTadyZ385oxSxKY4YVxBjL8VlwxuOGAuWVY8844Uu2On4/bOsjonAbt98G0i2rd8iH9B6MjswbLkAEruIrP1nloZESBoX2crKxZlCWjXlS09JMwhQkWqA1/MFJVAtx6JvY6I2qGH9lxCxPRwAkqHjTo3C82Mt+Jr,iv:kd/o+QzHbGruD17gFaQUzdZsCwX0ORgFLkA5z6Mt5jg=,tag:mntY3PPQgPXW3DbzvjgONA==,type:str]
    identity.pub: ENC[AES256_GCM,data:2DZ8T1EOU5MFUBNcFiTMNkZM8m4oUaxOdmcQaCz79IYc3DmL7te5gFLgcB/MTXSPGsiL5qg7AdX1vKskWKH5u6i4of5+zwFhC8x5onERHkfmAU1rzArDsUWFkquAe4Te9rSLHQb2UHOWqbuFeVjX3uuuTpw1RarugDfMZyRJebX1Yf30cq18SW/4GHJtjR/8C5HUGFcy9fok+LYCmXmrtr0btJ1ZeDligSWZx/DOMvrDwv2+o2UknCPaqjS2bTNEFzQyCPtZ6UUBvvecaw==,iv:lDmiJWAcahRuEazF7ObNupwev/xs6fCgGahtJxkqVUo=,tag:LB1zaKno6Rjbh0moHoAxgw==,type:str]
    known_hosts: ENC[AES256_GCM,data:R5P/XDkX7aqsvCYPCDd+Siv+woolcPC+wwJurMha/LB9T4RgcGOOJnep62Q5aux2Y1Vaz+MMvqXz7vIyJNtCN0FsYleWNFJG9cTVVB+RaIuFy0zNM2kdKVbUlQiUypprv84H07a/4VyeUbmY5dM8Dt9JqTaNR6+3hiqrsimcJl3PgpE9Cr9fkJD+1B26Xq/JDF/AvLXvHzpvqvctekrD1t7h18YoM0IX4VFn,iv:uLXos1z0/XEDFQI/eJpconfzGOiNzF5qqYI9C+4YuDw=,tag:qnurvTbnWbS+HRX8FSaWKg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRnVpZHZnTGNuT0tsdzZp
            OXhmWGVkeGlDWERwQncreDNoeTV0QkVoQUFJCk52cExwVFkwZ0xxSUZ6ekdvL2J6
            VWlaOTl4aGV3REtxT1VGODVOVmEydFUKLS0tIFd4bkxVWVFIVjljNldQUFJEejNu
            SGdEZFpQcmw1YlJ4U1Zqb2NtOUZUMHcKpApt8p3f7bxsKI5Zf5VNnFWxkkLjldfv
            PImhKUEHqDNYbgMxkRa69/u8rm6QhO1V1iw5LBhhUbmbgRpwFV0Iyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-31T20:11:44Z"
    mac: ENC[AES256_GCM,data:9keBWFCzrJDwKMnpJpz6jtZh8501x9NfRFEKdiE58kECrPmm889D4BsAwXNqDV8lFG5RjkjyQQmvzhHKeG5ksvrcujDG6+wJBpTeCp0ydILbWXa7dB8dhNQ74ZL1yqPy7ZqjtV/TXBaKBUa5oKE+UNpk/OcpeZscLlwCYsG55RA=,iv:vW4l3sphcKgoycY1s54BIGBbeTtVDhyiKP51viImShs=,tag:9W0tCdhY54i9T8N3D8ireA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
