apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LfZYfmi9Rz1J2LNoc48D7zycAlPDppcG00ewS9s0+ZPzLZ/rC2NUSZHFMmoAK3CkSL+D08shO60Ckes6Dky3wW3JDNhrcJJdFswhsJJ1CGEZcqacV8/KDGfUW3KPUw08cVptdXGjR1M4RnnEpZxsf4e7/ShWsfFuIsv90/sMwog+C0LRGkeCdzXUnnQWx0+dwM6QALgvgu42wUODGIok74R/avgQpKPdA7EHehNVoCEtZQjJCSnBDIHAV6CsDf/vQkK5S609Q2TdCmasrcf7Uhngo3oDNBJTuDb1vwlhGB0lcHatxG25blpwMrRm+d8U11KeiX9gqHCcdmTjdxdCSr2i1XOP7XLbki8xS93YpdfDHKpKIZN/2GslsuGUwiIM,iv:PQRkf4E6ehSEOlVklGf398OgS3fpn6lqfyznogKAkwE=,tag:sztbaT37SLsxml6+gLEuMQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:PEk3xAynbhrjOmeyu7LPDxCiW2RS4vnDClIcb37WL6DzbJajdqgrju8Aip5aWQW5HbafdvGppjVAs/iTIb9QvpXmeA9ozKzwvAv9EvsAuWRUKTX2LYK8IXDz7+1DjrYDcZeM3B1rcQIouU2X5ma1Qk5N5gviSnHMZWza5xbsTimrVGNVB6h1K+JAxu9iTBWCAYn5HUJngLHdIIxg52ny/6JQ9jcUIXbydKjrxAXvOrOU+l/HUvgifA1HSzi5e/qN05frY2zNXbxQEEXGqA==,iv:co7eHgK/MlUFkVOibSeq6QBVDazQpUOb+/LBIegNyQk=,tag:0KvE3yDjaewAnofCfeEs7A==,type:str]
    known_hosts: ENC[AES256_GCM,data:IooarpqqbE6qES4/MAZ9pmLCE6QmaKbp2E3ZyHzEQBw+W7nUZp1YoY5Dc2cjrhBj2InJqIOx8ZVX6HxD3T5EbMxCzg9880rercyOvHYDvZAXWduXstFdzVHqrcy+2rLDITpoDtWHpX2f2akxlUgxUNjxU9T97pCeqoxM528PkvHRTXr3lFzXuVm95TTMA3N7knq0fqK1TDhGLIamQYEmXKnW+O2UU6cqeFg0,iv:TlG0Q79+eRi7qYXKPeuycuqgD0kgUF0U+TkvCSqa+pA=,tag:nCDA8bEQCE9gL4xIN8iYzg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXODlpTzlBUzFXMWhoSUJk
            U1hFdW83Y000SmNyTmcxbWlSa3hKaEcydXhZCnRNbkFheFRpTFAwS2g1eXY1amwx
            a1NSeEtvZnVkdHJiV1IxdUlLZ01pWUkKLS0tIHluUEJ1Uy9zZlQyU1dzQUg4SDdp
            RTF0eWdFNWFmSVU3SGJjckdiSzZHNkUKKT8rAu+ZuoegOfmdpC+KYtwj/nasNQzy
            AOYJo1d2kdeqiZDhy3uJT3leWYPQHH92WavqoLeU/qQ3KujiRI1NfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-25T19:47:26Z"
    mac: ENC[AES256_GCM,data:4XzH3RHD9C5UMqWaojukX9DVdHhzhxXTb1cnyQoZW5lmxc5zHql3QTMkCjoGyH1c+p71tHxojh1cFPTk/0+qz+mrElNUBmPGqKtxmFEKcsJc+d8PlZJ51HHT2sw0tofEeI9picEi/LxVhGNK3eY3ijXOhFLldYekTmLzbyaQeDw=,iv:T2cpl1TSSLe7l8VDI7S8Mybz7tQWaYJ0hN7F3LyiYnA=,tag:TzgUGZmiUlnatXj3UuaNgQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
