apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:v+sk2yFM/9jg/66XSL18pMFLUuUoB/0Lk41nmIsl5VII2lFXHhZy7zDALDXnvzX45oB9GO1DPOhV9VpSRK7tgLSoI5rvMN/bhWsSF+l95ZbozDPmqc7pq9Z8LUQ+WI5e+0zyYl9ozM75kziDVU/z0i0mqxuiupKb3pUxakKajIMQ+/xF53zBxeVPOBTz8fLCnPh2Dc7qvxlwCN1Dx77KgGsyPhqOAHrqt75qAGsUIbt904n6Vvu9uz81ItgxPqodEbz2u2Xfvuxje4UW/KoIO4pqamSRTdyf0dtwbYXuKYWPZZNTQYgFa2ZFNC60ldHEDDBK3MzmGqWcv++tF2Q5q0xvGDH1aeKLsZUP+/18/eSBdvDoDYuJvMiZ5HOh3Ayq,iv:BSzFR+E5okU6t/20QOQhtyHCPgXrcvaR3p00A4TzLNM=,tag:ESifKwEaSp0RMfpcmmHNOg==,type:str]
    identity.pub: ENC[AES256_GCM,data:8SgE7qhUbO6FLiF9Prji7zfQvu6o4t48m98grX0+O6PjPCM7B45Dv1zbe2WjxCzKx1eYuHCOOcdF/VjYd5k1PUzb0QeSGHPb+bR9ML7f/no2bVqdGDj9r3yg/+4jN7yV48LZeHDN4Iz9yOlX7JKrsbu8KtP4ePcJs9RbNa84sxxesIcq6zAmxKzSIAtNxQzVxNHpDxNrX0mXz15byG2uxqRrw3n7508QiPdW7jpNcdadI/PGQ5ack2mOfETMR8CMjWR0fQ1PLWH9IbXPFA==,iv:M1FM6TPQn4VPqFY+fvQIbkEhSsSrJtcYzMg0zE3RXLo=,tag:IK2Xp4AVtuCX1lTKRY4B7w==,type:str]
    known_hosts: ENC[AES256_GCM,data:/5ti46Z4DEeDQoCOFAS9eJJHiaU7Ci1fKXu2dwMmYbox6s4V8VJmu74Yqs2no6O4DYk3MjdTN1mTfVvAovTqaTAS80jgK2XhfpVN31cYPIrtkT9GmaQGJqBipMWjc6OT8E/gHMUVQdGZ/BLN97oIz/NwRDYyInVISKIuZWVI5qdF1C+rdR6NLBLPP6H2lvZoTUrbNiMug1yDNgB6xw8kyNdMhDR+19bQv6dv,iv:Dc2Cq6I1rQDs/dyD+kK7MOXyWbosVVzSzTDoukqIGs0=,tag:7AzA02Dhof5QFybeiKEo5w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNm5uVlQxL2xoclN5V1l0
            MENTRFR5OTlLbGZYMjBNYnQ4S0pZbVdhS1E4ClhURkFQR0F4TnZoMC9HVkl6bW52
            RUYrUWhjTXpDNjdreVVveSs4WXVUajQKLS0tIHdUUUV3K004N29nUW9vOWtnVFJ4
            bkZUM1RnZkc5VWErM3VLS2pWZnVoTmsKVJi1uO9oRvaPZXVm6klQhS7/EjZnwsmw
            EGar0lSrNpTNBRhhR3a0k+2KdGtvu14Ed4CBn2hlZIqFeC1a7JMcMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T10:03:50Z"
    mac: ENC[AES256_GCM,data:KZXRPRdKtQ1u2AmVIRM24aywRpi5AqcSDz7MSz+4EXTZ5FRJYrb+CPxZox3GOgYHqWC4WrVdSPNxSVfpod5snsQ+HVHIG87UkLIaOSkz79VmpQxhHLXEPc4SgGneQn9G6AX7bj1UAkJqg4FzyBpuUd6tZ1aqigG78g+5UPVHTSo=,iv:JgS8wo/sWSBZeCsLdBy+LEDxHO3ptftSQRa5/1YKIWk=,tag:7HHeInsnmHkBQGvwPPlC5Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
