apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:X6qw90dl9zFdZGd6fLXvDEa78jFJmC+L/8tA5sVIMCG/Tm3FoN+hz5fvuoadhNmxxHjtOm8KA1L/QUkP7hkE7f0JsjrjTOCBA1T3l0QrORneuorLibO8HlNpIUGvIWDfxjX8kjaIeYy2Efhm3SkC3yacRrQLGZGxEunAQ1xu6b+eTCMRSC8g4gU3ivTaxQmt+Ah6ieCyoG2VHu/7UW642GoFsdHxB5ZzanGI0WpFpevSw5ur2+pXEkG/RR9OP/uTDEj+awKua0uEkhCPQerLmgHrPem3pbltncuUfNf6waILVqN7vfjWYvyEY8LDxXJh9yxCCNgFoBwi5mz41X3dSGvYwKzxX4DsdfIu/iLu3AcoMKPh90bn/cuQyfgZFyMk,iv:yEaBvQtZf2V98PtpaUkWfOXpWqdGOMkKfZwACCedJqU=,tag:ttsel+IiN4pwBs3bxFB6Qw==,type:str]
    identity.pub: ENC[AES256_GCM,data:jUCpW7a66FUaxY1uIcY/gxNtyBoOd9MIl6iefUZTRH9ZeOiczvP7dOGA2jpQ/kQN72mVrh1J8OAuUyS7CVmoWoEK/jb8BaGq0QLlLMAYew6Ax4wSZIhvdK4gckv/O4Nri4XyiPObg2bGZ4nEVJ2oCcDa1Fwmv8lbfnLfvSJ1t729pFY12/ViSPKMlYZtxuEqYuXYym8A/B4eutp0TkF1Y6VzxOL84c73RWGEK2Is5+n5Pt8q7W73CXibfs2oudM87CrhH4C9KfkCysZ+xw==,iv:+vSp7QlWNXH2Xt8O7PB0gfHFuC/nv2SVjBIYimK+lO4=,tag:FEXFWs5jUvA5TKq9qVq1UQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Pp6XN1NO2KNnFJClZBq4UuJaTHeP8aNwARkFvwjXvegtiD4Pf7ft/dAba4wlNCRmiyGeuK+emf84TEsbqGvN1/Q/24lbSnzU9HF6JSe/85OzUMCoDxntsEj3wOViH9ibBs5fhZwuR7jK7e1UabjE162zUJGsq34wqDUXMO7NhcCy5Ko0NXUrGmEs8dQl7E98n+8wl1m2+bo10T5xZ5taJ7Ot4/ZR/ihUmYoJ,iv:mFR6lB7+izOKWXJ7o5sGZdFnIrc4nq2pLt5OhStE3PM=,tag:jYyHBSeb/kZ5HrRAJo8/3A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcnFFTGtaSXdwZXJuTGlT
            VkxBcG1uWnJQNGZGUTcvY0ZCYU5kZ2RUc2trCkxqdGM5Z1kxalN3bW9wVG9ZcTJI
            aERTZDYwOEVhMVU2QlhlQ2R3TVFVV00KLS0tIDR0UXdWZm9JY01VcDg4QWdrL2Uz
            eTVxbFBxeVlGVWRqd2pGRTUyZE5pQU0KARPOiZLErn+c8yhaWLU9Ytgcsfa9cCrw
            L6mvH7aukGoAuSvOJbxU43GKOKkitkD5V5ryK2lNfOEZWNeD2dc2GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T07:51:21Z"
    mac: ENC[AES256_GCM,data:j+Xto/Gd2oOE76GNDj1OpEZeoZKFlNYRAmThRSYpxppb6mM8y5JSSSufEDvlR3UM09daxQgQnpSLTOTt98S7HvS7PYkVFsLdISOp22GExhMjLFgqZPmddWrHIbdAsF5BMub4LHV2VzauA+YGUdHTIgKd+dgWmCKPZa15CHlPSEY=,iv:MvaHJL7tUwY+Adklb4iorHd1ZYFToCEwJky2UuRa5Bw=,tag:Er+leldOArGeh4IUyXc6LA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
