apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6k9XiuMTh/hSiXufqH4qknkn1tJt12uJVpvRlq24PIIdgIU0HIu2PYqKvX5nF9ul00snBDHai1ktpI0ifJe72eA5v0ypCnMqpQFmkQ4R49E1FrNGphDFa/sGVBiE+8Saa6IkaTlVWW3yizpVi9wtLUKCMMTzm6jZvmnWG8jXF+5DwGEKW+5CC709jDQXpc/LZ/BJFwjunGzn1YmVS1rtU97+crgreXOngIBjDkuNVQ+DM6SLf/UcsN5rvJRfOl/KjfWvxX65XmmES71Dw9Kc9weywPezlgMDKlM5tAb9brTm5cGLmgxNkKlw0DKEc2w2Ca2xf7NSf1S9FjAUmYJOiUPXDWyWr0nktlAT6wOXXmM0k90pWYF9wVmVBWVY/HUm,iv:7XNWzPize6QMmfvYb3/JD1+eRkZbkjhyp5KJpFVoHPw=,tag:bVe8Yx+wFjRWB4xzXnR5Bg==,type:str]
    identity.pub: ENC[AES256_GCM,data:twpGei6rZ/JeTut5D5dI8U+d416rpNP3MKS/euM0qXT8OW77EbECHfArpA/ba7Mm3lBKDDe3JoEdmzWvu8tJzBi5RPyv2azj7UUH6YPaNPCsqyB+msQ892hcyC/x1cFdiowZgmgfLDjGNQvNHAPTegpCE5FjE7RPzM2qzDp1MLWMF1dRVIa9DbRUnRjMwzq6NHwgUXRrukm+DP9VCSHnnKpCoLkaL5eIoA1bSTZvwPazyYxK1PfdmQaAs22HAihuArH/ROuLQjd4XzeB+A==,iv:MqlTI8GeF3Zht2E45yKXMPssKx5K6ypNSVBfKkLEptQ=,tag:alvl+RxILMBk5pLMBjjIag==,type:str]
    known_hosts: ENC[AES256_GCM,data:VZylpDWsbeILo1ddu420Fyu7CFbv7D2ll4/B+XjuNj+LPe4WvH5dMLAuL27hUGXoujYno8N57965Qhd+GBKNYNiOniZDjiX0l8MMnC0IW+MG85GPaGo46qCrB5hnjp5y4PVfRikhjpolo1g7+EF8ZIeNArBal99zdtMCmLX1na6gT/JB7BEwkLsylYDMVqO6O8ZBR2rVOXxJDEJZK/2GGrbA+RKLR+chbPZP,iv:PVkO3jeHsL7K0HdbzLlgmJ/QFPY/NWjv+faK9yNTKH4=,tag:4Wz/d+SR2HCwYEgNVLIcUQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WkM3VGhpN2xXSXJrV1hk
            Q05ibjhLTmlSaHkxcHQwSHVrWWZuNm1BZGtzCjh2cUhyMjZaKzJHWFU5YXRHcEpS
            OWpUc1dtMDYwRitGQ282ZmFmT0g3WmMKLS0tIDhsT1NXYXlUaHFDbkFNZXBFc29N
            UXhuK3ZseWJTSmlhWjBJRU0rdFFGMmcKFVDTzoI+htKPLtyEX9LZsjJPxo8EJKUk
            h0jw2nfNpad0DfxRJJtF8/v+Dee6oGhVlKBbz5ApI/J9/mtkosVaVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T10:00:27Z"
    mac: ENC[AES256_GCM,data:9A0FAkO4uHpLVauECkAa4pvszfPajeD3OniD7Bpxey03Xyk5TxJaX5td76+zf30+b9qsv8RlGNr5Cl2HFS961UiDpva8hv0Z5I/x+h6jv2V1+Pn2fYF0auUqh6Azeb8//GRez1g5LfjRdZrqrCwM18/TiZaJ/hnUEEA6ALh2Ppw=,iv:wwbNmGWIZG/Tg5DksfcuxPlA3mMHS4LX/SawKY1+W40=,tag:Tvv4OM+tLwd1HDbadmKpdw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
