apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:G2Ty6ZUaOryijB7pdnwmWhCSzlgtkmEdOSnhMDTc/YcPB/FE6ZETAcckWwrVqNy3sCUdVhFxT5m8Dr6+LCYDxrHO268kqH61p1GSV6SqfBudjjIC/u9n2YBynNe1iUKpxXT9bbS63M5c7FkENzcpuYmN7lhhe7bcd8NVOcfb5lw0+xjXHnT/Oma5fA2ZrZ3MMi5NgbCtlsPSAJXIVKvWQIpLUlP9qLezth2QiIytD14nulClbScB2PCr0VqTwY6+CnM9VXHvezpdw8hdHiL0CATSBL6j9vP2HVjFWpJefW8iJVj+waqtX4BruXjraCZ+6smjlAKntGlibI2iARVlY2TLfExNOE7IHC/HFn8DdZWXkBMHi3E5yfn788CwwDgC,iv:JKNf7igC88vrsl+fiNdhbyg5QNAZo82Bowt9paag09I=,tag:tF7VmKI1wr4giYbCoCkudQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Q3RJpYVwFLzkoZOfPCwfF6bMj1aHy7zypvTsyyyYOJ8qWrrKzco2VTMT4qDajEGl8xidyzFcQQZfAyE0CssVyKCRVC5u2HUuJmb8SRz9RfqC1SVBNMgcEZuFK3oZn5nhFM9itileVZUiad9ZevlW1Kbf7W/XJ9ga8I1ItSuVuFfEkMWB0CIufbS6JkQpG2O0caVtm/u9zJH+Oe2fuHL1DrXbgrdXQzBmn/uKwV5fIwa+x8TvWPIDbl27xhVwRHXSJ833TY73QUuz17motA==,iv:j1xSiYhJ/18SECA419BrTwOskf+CbeG4Pf4BCEJtxZY=,tag:oN4npWO1n0m+UXC0jFR/xg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ArnQgDo/Cq/ti7inidfygx2xe3pNUyRqgSHhrm2l8QZg1BmD78zowzN/qUl3AK6xfy1CleMPG74rjicQtT47kuOrpSfCimv+tD242JEvfKxVI0Cs8jM5WY4EwEckZOr0v5yv4TtG8ECCr74vUgK5wO+V2P1x2z+1m+Tk5BNmtAEVbfUDXyQcL6mpoG2tVPg274bIAQoMaz8P+bTAeKZGDOdNU4mlYZ2hDxhC,iv:CWYisdIlewVX8s1W7qj+6KA3DnKA/S7QlRNuc0UjSKE=,tag:aNX/z9o6hDd47obWvARe1w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeTFBbnNPRitmQzZIemlM
            aEZMWmtUOEVNK1MvN3ZUZ2xtcW1WbE83blRrClV5U3U4TFUyMkFxbFlMYkE2L0tr
            RXQ5KzJ1dm5wTlR5ZE9DMElNSi9pUzQKLS0tIE9vei9HUEJ6WEY0aVJhdkR2RU0v
            dUZOY2ZlSmg1N2VWT09DK3FxcXlHZkEKgdUoduyy9fW80JLqf+Qfo8VSsSN1Z7F8
            UaIQK+uAoXt46VjUvQOYY6+SAGSpjFP/mxdf5aCh4SlPpBjPpCceuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T10:30:36Z"
    mac: ENC[AES256_GCM,data:0uaDLWoCf8fgdWHQBDfvvZOAXzCZKvPYj4q2fv0T9eMEiB4rXLJSM4IV2pYxA8cKW+tU9atKORkhxHKOSO7i1gycfMuVqOIKw9OjdvuCg6tCWGkUaUccwVbxXKFGzJusTN3VikcEtNgNEM4XQ5+A06kK33xGFx0n2PPyz66o5W8=,iv:PgLW3wtug6Le3GZbpuRQ2c9RhHAhwNCYVTQWFV+0X0Q=,tag:K9EArF1/yF7muHRxRzyUnQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
