---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: gha-personal
spec:
  interval: 15m
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: actions-runner-controller
    dockerRegistryMirror: http://${DOCKERMIRROR_IP}:5000
