apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:3CmUfpixLdx7n5NXjFGodvJ8n62P7Htv7Lu2a8DUYx8=,iv:LgV4SeqF4QQnLPOOqEPaMhSXlSCVN+sL9k+0phEIxPM=,tag:T5bLY4V0hH8FgtT9F9jiOg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVXY0aFJ4U2c4M3MrODM1
            Y3RzWnJTSUpVMnNtRUNDbDlxNjFSNnRRbDJzCmxrZEZoZUpnZ3FwUkhaWE5ualRT
            U0U3SGJtS3lKZ0RpR0Njcko5N3MwVlkKLS0tIFJQWWVYNmhhQzFGSTJpcUVOMnBN
            U3FnanhLNmkxb3hVZzEvd2cxb0d1aUEKw8tgQbSnQBqa6x80DDvpSStoAga6ZrDX
            L6WGekIOvrXhvnE5jzqNDCqjVTjbCODJjvzOSzD5AKKsmjxNbYtkew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T17:06:55Z"
    mac: ENC[AES256_GCM,data:6oMH8yP8Tz2fOMdxSa+E646aD/nmSflHbXfyUYdcBj1Tud/EFh2YiaDD1ket0WQwEOh5EE9Jix68esjQTrg0NsLTGv4trwMCWEKkPfQUoUXurXOehzb7ToV9zV45DLZVX5oEF5O2VqGageije0ROW8aGu2q7/IrMtkcYufZ7m6Q=,iv:85OmJyIni1v6P6kUTKbOE/qUIgkEd6zRbiFF+LYaapE=,tag:/yfE/RlAKVLR+JDDCXVFrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
