apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:z50uyXo1/qa2dVOE9Mei6xmVMDtygXktVGRfn7vpmSI=,iv:0n4RMQqatsY5z0elP4HaAP5pdbHb7iGcsrl7yF9gl9I=,tag:mI5NUFEULClKDoiRq7MDjw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUFc5c3BmYWVmY2x3dHhu
            RHJXTWgyb1dnN3JxL2pwVWpnWkFheVVHYkd3CjQvaHBQejJGSmluSG13bjMyVk94
            VnZkY1lxSGtjUDl1N3o5TXN0OEQ4dEEKLS0tIHhZMUFGTlZnQWhYMHFuZzhVR25t
            SThidWpBWjdPQkNmRy9CbE1KTkVJd0kKApylamAenf4YiMJY9TMpqVQV7JP8l8n5
            qinY/6hpl3xrH6+C9lEoLezNdVh2E7hXq9XvFQZUkfdXfzW1lYqlLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T11:49:21Z"
    mac: ENC[AES256_GCM,data:GGAuIq/9Txre48wRvyn16V9vGHPmgxUCAgq+Gv4UM23zXyx5FUGRwY/55JYZ7mWXVHkrCjAjC4r3L9IGLygXp8bH25PoWPTvO0tT/JUpav495/bpdwMgozLGloa5oQ3LJ0MT0Ej5/XT0hagtPAniK/K9qkfcEcsE4iCUs8KaA3k=,iv:dobl3ivdo3TFxrkjHvXYj5f1Uiuzizq96BjMl2JX0Q4=,tag:KEgiktO5fltFDz6G25qjvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
