apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:2nGnLj+W9GfsoT3CC2abHp0zKzkSIx1vMW6g3rHjArg=,iv:sJzJ9TcVz7W1yreISHLEg4vEiUzfBueHO/w36MTgpl0=,tag:w8G+74ON5hnGaX/xHcg7DA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VHArV1F2cHBRSGdBRGk4
            bytSMzEyb3ZqWmRlNFo3dUFZVnBNd1RZQ2g4CnRZeXNEeUY4ajExYzlMck8vQno5
            V1cwbWxMZXUzSXhzcVNUenVxZTZtdm8KLS0tIDJONTFaY2tDNklZTnVWUWxXQ2RE
            c3pFalEvRDJMMTRtdlpBL2VnQnNzNkEKqJ2/j6yKPOy7N55/vS33CmPbu01/lGa3
            +ROI6wLHrHFo1AlnQSRR4+odKtkGUedZ5wqXA5UF9Z1zImcp+G1htw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-20T10:46:23Z"
    mac: ENC[AES256_GCM,data:Vnds4XJeeH8fGUF9HkTTvSrRRJ8bM2tjTlhqdydzWG+DAPcMseR4gbwlrNFhshiSvBirqooRWuHxnE2Nrdae/KJPipPMFb1e7ceDBbO1eJFAoIRW+FrNMTgenUb1XZNtEq4ibUP8EsVY6BYtfk9+t4KNbwebaNWhacmEqaKhLTs=,iv:orzSsWMdTrztva8XdoSyFUcR3VYl8REhlEprVxXEP0E=,tag:POhrRjyO7+86gO+zUy0yew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
