apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:KxqaXp0Hl9p+yIhs9oe2tn46PSflH8ofhb+Wfa4d10s=,iv:Os9aTAeaHjItFc+uBOcWsGFeZCL9K5GFp2pVzTpBDtc=,tag:bl7Q0+Y9v/amL0A48v+sCQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPN3V5eWRCVGJiajduWXMx
            dWZkSTY5aUI0N1pRdHB6NGZUUCtBTmx3Qm1NClBMNUJWUGF3RnVFRHFKYXdRZ3lN
            L0QxblRxZ3lyblkzUmlCM1VtRVhzUncKLS0tIEFrVnp6ZC9sanpFaXdHQ3pJTHYy
            TlFuVktBQThXcit1cmQ1S1FSck1iT0UKY4YHp/Aaj3hsJKSWtd4kGVFYrLKfgg6y
            jLUU0NtpjvMbcl7e4huazAsATZbTchAQs0JdAGsY+8w7Y6QoqSorbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T12:26:04Z"
    mac: ENC[AES256_GCM,data:MU0D8Qw9uSw8hr+pudym/Z3EkUeXU3HEgNtFWx+BozPZ5YtPQZ5bSDRSeiKecsttJel+fk5dBse+GyW7VPzUKXoOqrktWwmxmOVJEedaX0Nd/WfOfVITsgYtREVouisNcYPutjT+AGRDAT91MOVj0XDIT1SuRtfBLAqE2ZijrOo=,iv:8itUPydgdj+XpaI7b8Rw9R/UtTINie3lvZ+i6MuSTxk=,tag:mVBQ5h21VN/1pPkUQiM8iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
