apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7j/maWJkdX6CwTC3/+w/aSBDZfk5N3mPxnkZdBaOosM=,iv:MIOYsz697JZLP3FBcubCzHjBmE/jb5qp8AdD+Vp4uQM=,tag:OjAi6RRxJMcS29it88IZOQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcElkN3M5STJvRGs3eWl0
            eDBBYVFBbzFWbS9Tbjd6QTAxRmpGWjI5N240CjRUZ25nZDFXcjA1cEV2OEtWVGFE
            VXJrU05SSzVhTk1XUGg3blR0elMwejQKLS0tIDgxVVpMRGVtcFpyeE1DT0ZKYm55
            MTE0STRBVm0wQnhoQlNyRUgrNXpVYmsKUPlkkxKzGDBspyY+OsjAmpyJ+dOA2FT5
            hexfzsrycsxsJsfoMOeZ8/+qUxoxK2COUlGMdaL4o1xvRK+MzoQ+wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-07T16:15:31Z"
    mac: ENC[AES256_GCM,data:oVMilzZCGbV4VBC8goC5KDX/3/QTtoEl6WNbj2l4ax4vTItq4OPSIIYj2tyeEHcwyzTJlifobEn6WKW8Qz4PQfXgWOEp3UfZ7hZuEvt80t9JuE6khVwfHCG/pWXgrhW+NpS279U5/EEKr8L5UxnRKxqb/ilVsYLeDGmWdPdxBBI=,iv:tEoxRxsatfA0pTH2uaExR0lBjeSenAFeZGRNslLr3g8=,tag:RT3uizOoIH+SrWnVmIgE/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
