apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Auwf7Jbeqk+OEOk5kY8G1Yyt5i0HY1aLpwobtXwp840=,iv:dnnxPPV14/9BQNrqBp9MaVgc4r9yQKCIn5XSXEQAOPw=,tag:+FnOcu+n3Pe9mphj4i441g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL2orSndSSkFXbk9Famlx
            RVlsZ1prb0E2alhmdDNCZUlBSG9GY3Z2eWlzCnFaaERmMjdtNGJleUp3eHI0UDJm
            SFQvRGJiT0NEM0RzVmdCWmJrV1BYSDgKLS0tIDNDSkZ0dVAwTElKWUNsRmxIZDBN
            ai9vQWlXU3N6amI2R0hHUjVCbXhwV2sK/z1C6VIzOwFLwq7zyVOOXxYEXw/8dq/j
            4d11vDN71MJL14ZPnvwZcKckRAXfQAlFt9ABLBfmiCwZV/wxFL/mng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T10:31:32Z"
    mac: ENC[AES256_GCM,data:9XbWHNqvc8qA0VAH1iMkFeoWQP497FccTLpcr/JBCMgE1X6vW4d7/VtWdBWSS2+rPobF67+r3pU6nYvOKB6Tv2W1i7pmplBOC1k8fe/cOH/XWlqIl/r6CJvRienYoiC44XSOuan+92kF2BuagQgEuNXfATloU3MYV/4gLml72ig=,iv:zIZ/0M8jXwIBFCS0B9VpmyREIFh7+SnAlXYDzE+O1UA=,tag:YJ5QdmYyvv5opLMDG7d+YQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
