apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:M6NwBSvXAMzcZVerOT+R8yl8ad04OMZ5pr3/6QbT/ts=,iv:LuGdPmO2xPmZ5bQMaP5i++ccSguVa/RPGYHkOELM2kU=,tag:Z8qkfJ5rC72S0PnRFV8RDw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMzBWNjFMSHIzZ2JTRkJt
            NjBYYkc4dXRwVHJnTG9IWmtMYmFiNU1nSmx3CkhwUEVGOWZGWDNIc0tIT1h3SSsv
            cnJPM3RKRUIwNW1JYnp3L0pndTZEZncKLS0tIC9wYzJXSE5GdFNwS0gyNi8zSzNI
            YzlWWTVQNHM3MG9SZzVFaG93b0JKNE0KB/xOs0c0yx9DXjxTAg7Yvwkk9NIV3Z/B
            9scDDEWfL3Ff21fIGsG930THA4US/D9pemwRKv/sdJ1Bpj2+q1OHqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T09:38:21Z"
    mac: ENC[AES256_GCM,data:A7c3nEyyFar1jvyOvux0JjKoc4AhZLBnuv/O3u1AIzQXVau3tnB0RZipNuULqAviiy72RX54Ej3Yey57jF81H+0XjfYDt5GidaCNh76eWjDZCoox2Vlkv3YF90wen7ttrpaBtnvhgRFYXuTu0jFXq3t00X5W67PgKLYF9cg49eM=,iv:VwE+I+ib794NuGTfcwQcGRDzip94qJ+Viqx4YXf47/o=,tag:Kut4b7g6AyvnlcmRAEoUYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
