apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:XrXX51PvycRGJRqQqf5k3z9zX69TRJvaAhtUkBqh+jA=,iv:s1CXoPln5dApPcm8i5myQlxuCPIp6GgONbV+7bo6w4g=,tag:jd0KKRrtcPoiUHxDbDPBZw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bERONElqbXZVNkFEWno5
            L1dmUVJKcTBVYnRQaFFrNzZwNVJDb0xyM1FFCkJMTVhZVjIxTWZXQkJENkgxd0FF
            NVdlU2RCeHFqSmVVdW1FQnFaOVUzNTgKLS0tIE5zK2YwcDcrMno3bUsxUjNtL3Yw
            Skt6bnpkUHVwK3BtTEpqcm93RlR4blkKP9CVdhlT9uSq73gB8Dja10vJJWIbl9Md
            6VrIGjBdgda22A+uJA3NzE4F4N2w6xULb8ivnbrtUTWqXqcznpFuPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T10:07:37Z"
    mac: ENC[AES256_GCM,data:4Jsv0nB6v4vVZHepEUe+HBsiDYfkdzCe9PPSzp01EN/Lhn/av/yEaC0NsuhzhwT5+avL4YGo0nsNB3xiHtMomgY3M+x0cdteslp0UsI32VX+I3uTMPDEPY0tMfM+0/lovM8UTnvsrqJ0CLARuy1ERMtfyHsFp7iHhWMkosibcyk=,iv:USGCuLSn8CvtHn2ksd0EqDq/oWOxsdE1PoCIy0zGsO0=,tag:yeCvWJKbx0XpVsngSMQ/og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
