apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:kCBF91saS34+whq6i20bLgAMkfaDKawmIXe2KXR8tfs=,iv:5XAJktI4p4tBlM3ONHhVKyGqulyY55OkYwDXPAkLg5A=,tag:PB3CGuVUbY0eoUcz8z+UoA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOVVLZW9VTnFJdEtpSGE5
            bGhwb3NESzZpcTgvYm1vZHNQZFgyUGJKZjNnClRuSmFxVFh0TUJKR3BXditsRno3
            NlFvODB5N1lyZ3Iya2ZEdms3bW9rWTgKLS0tIDJWaXYrcTV3eWNQZlViaUN5dThx
            VHVSUUU2ckRsNFVXdlhhWnc4NzIwWkEKWNcqMl+Dj0TAVhov1gGT8hKBIMP86DJQ
            0zb2FlT7v3avHwztOZncdI7cRTllTVihE5KOEaXUmoh+FNOWqn0uLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T14:58:20Z"
    mac: ENC[AES256_GCM,data:TlRZbn3FGn/zlBnwICKBzAPvoDWH6cz3zfytmxQi0D2t8Q4i1WJEZCvmG7eP5tE22MAurnCUBp7ZPsPfMjJDhLfkfzkbCXTGe1Y0rpU4WZUbu5McQnEA8qwmKns+U8I3GZD+sKZDTVgfM60rK9mLNDIgXqcw4DCfX5bshLOiOQQ=,iv:BfzAR4d4O0yjMRW6Fw1MfqR+nQrGx7bg4mkENLbQiiQ=,tag:BgN/+2ii/SmET0S1uY+1UQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
