apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:DPD6ZFD+eF8DtZXcBEBUNnIkQFfKVkY4LLFTC34MN0A=,iv:P7ZtxoSlDGFRUIcjSNFHa0zIRO3j1ta8OvNQqZuglDk=,tag:1xn20/Rz9C1MVVWVXxOS0A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReWMxcFpFcGxnMmdTazJt
            UXh1OFltbit5SFgvVjRFSThDemVoY2NxcVZVClRuY012cjNJb20rSWFrbE5EazYy
            M1RYSmNra2dmcjd2aU9nTW1wazlNa3MKLS0tIFBPZWF4NWV1RmxSTjFzaTAvQnFv
            bVpIZzRXYUk3b2srOFQzRHhKdFdIZHcKF1EFg3oW5R9P85k1ap6GeulfElMT7uhm
            7dcan/wWOzJpKSMLDs405OLIREciWe+V/WhGmiW+LnYs8WQMtconvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-20T10:18:45Z"
    mac: ENC[AES256_GCM,data:nxJebpP6hQVX3PE44hEl8nJhHG3HREQYI7ge8VB2iDzzOdIowNJq6JLoOQMKmQXh3sC9vFyQqcRHOAOY+D3bJl8qNs8FmZGdKCVNiaJ9ElsATp8oL50RvpP6gPFVm5X9CfB5OcfVfYb7781w5Xh2urgO9czbOv3ryk/4UBEBP9M=,iv:Qn5x52QafzdfSaSsZInuKsXOAc1yL1NCb0NWdPlQI5A=,tag:PFLk0YeDgHVD/r1JiEao/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
