apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:tqJR0CnDhZsmbh50cHh0ZvuKOFX+sq9tIGEnDdoaL0E=,iv:Y/iKIR2xQEPaIiZR9fne6tuEUxVBVNqlBh2gwLRkmKU=,tag:98fPmL6jXM3Oa5Vv4EGG8A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOFJnOS9peUtmNWdnQm1y
            TjhNZ3laaFlIazVzaldJcHl2MUFFN0I1L0hNCmlnQzFqbm1DZE1pallOc0RockND
            Q21NaXhOZS9LL205U041aVcvLzhQM00KLS0tIFBWOE1vamw0VHU5c0RFUm05dXFV
            cE1OTExXcHhOVU9CYTk5bjd0ZWh3WGMKzi43tD4/0U7b7YSyjNg98bZOc2Lb0Kw0
            i/dElzpJU/vgWf0sUhicpwcwgTZQKMUsRfKwvI41Fx34dake6LgD/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T07:51:22Z"
    mac: ENC[AES256_GCM,data:76KwVF8LfcSqdcA77dufIrVk6I1N7mKMcw/2/Z6a49aX5x8aFFiGR5x+Dgzrs1fAPBpL1Gg9kgtN4VibnpslCEDUz8/rwpQErvp4t0grSq8tz1uRsjZk/EIiYbTI/K2mR5mRDct/+q6lk+F9BJW0ws7PQxFg4rcB7lCvDVePdxg=,iv:7UTLZ7hzi1wpshRyuYpFL5utINSKWFC9PjdAnoZ62vU=,tag:ZcL+OicYfKf/XedYvrO6pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
