apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ldyD2xyYTQ2wUb+X9F4tLiLSQD44cIG8i1tcEUOc6mk=,iv:YB1+u60ejOJ2kLOgPpeTGmPEpLNMGKeqFMxkiWwjkgs=,tag:Ph/w7jcfkBU1d3Yly9qe8g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvM3U3dk1WMmEyVVRxRkF0
            SnorWHljeU9neWJJcGNUano2Ky9hUjB6ZXdRCmU2Rmlwd2V6R24vem5ZTUdTRWdZ
            TWIrVGJ6eXJmOTNGM3FIWnhEdXNRQlUKLS0tIHRHdnZObUdVaW8zRXQ4ZFBhenJQ
            cVpXVzlRd2dqbFJpU3c0QlZhL3dVbmMKSqdCx9wH9urql0CNmGXKc4kNVr/0imxo
            /hKdxBOgmn72z9AshNU7j3vkeCBuiyScH0MqIRj+GP5WXhPkItWirw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T17:08:25Z"
    mac: ENC[AES256_GCM,data:ymFAP2xBmnqjtw7zrcJCUZdL9CthlRD5slXZgb+goI7MOVJkzTxZpHxKh1WKd9d5w+5pUbrYK0oM0tm/R5IBDS7bmx0qMR0KkojTopzwG+Ph/RlwqmLN4gZ3HebnGqw9MCb7UWb3a2hJB0IxmhDa2PD98/9Be8YpFUed/ujdqHc=,iv:E0gw4SSPATuL/W8wL9yL3LG7+J49phQNdXOi7vH7Yhc=,tag:n0g5ahiHS1aA+uH9PQcpCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
