apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:2bliY0gvebXwdA1y58DA4mx/+qufnufgEhetaTiMd5c=,iv:FFyxg4fxrCo/74af+4SHtt0u9tvpdJqERbatlOlXpwM=,tag:uE4Og8q+S77YeRx2Hs5i0w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK3ZweGx0N3RjUDRJaXJ6
            aTFHR2RDVmVsbEZIaUkrNVBoL0hnNDZtRmhNCmIwZGRNUVpoaDd3MVNTY1UrTHV0
            ZXR3ZzRpZVFCL3JTejV3bkZyZWYrb28KLS0tIFA2UURrd3VaMjAwcUVET3dxa2ND
            RVlFVjhsaHQvVkRTN3h6UU5LTkxsWmcKASMTxnqTUumItGV5bhuYXFCdmu0cz+oJ
            X3+cxt1RsVXZgjT6C3B9ZXZrT6ItLlYPdTOu0mWh9jZM2zR68XXm0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T09:49:39Z"
    mac: ENC[AES256_GCM,data:Hid4N/VP+59wnzN6Efd8y49T41YJijy+9m2bMNcB6Dcu/c+7+gpBwNTHoSvid/WUIPDlh+DWeM+wUfy0zwRAc1NNr7xdSBPGJv/5I+Oaa2iD/kTlpz7j/a0TED4Y/Tqz0NKbtJxCu6jUjOKizfSpgexsaEQH0+EEJl3dUoAclvg=,iv:1LRSmsPCJnawtQO7JXZ0J6pxG0BGXPVHtdGq1XkDHU8=,tag:z2XvpWO/01QaZJ6RCGr4Uw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
