apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:I/bAlnWX2PVTuScTndeXyIcdYxAxr4wOytDSAxkuphU=,iv:TgF9irNH5K8zBGF9+Ri5qkD+zXlPdBdwOKfp8KTjeHo=,tag:aa6gR8HC5cD5V2gjJiERYQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeGRpN09palIyQUJiZEJs
            YXVMNGpPY1UxMW9HUVNIaEpFOEtNYUtQaDM0CmNIUytjWG00ZXQ4aEx2U0d2L3Bu
            c01VeXFLLzV6c3VVbnZVSmhCSDlMd2sKLS0tIE1IcENvRHlORWlLaWF5M1c2bk8v
            TmZreWZKVUdSZVJ4VWsvNTdjS2ZrM1EKeq5KbDYFryLngv6gw+jy962jH/SibdAz
            HhkimrO9tHuIGoWpf/Q9ZI9RTv54PHkH4br/wC41N+Fkck+55l60kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-31T20:11:44Z"
    mac: ENC[AES256_GCM,data:HxxlUFdq1dvloYfxWIl31+gf2BR2w2qVPrPyBTbxNUJMyvruRvRcSaafb//7kKGnpwRutj66lAcnPK5zHqqvXl5l9E1PPOlw1kFYXcwfmpfxL1A368v9Kd8miwlsq7Np0lZtyJAJhbSuXrxtuaNnisS7mlDWbdZ6TkuD3D8iRGQ=,iv:PJp7UCtsHVxfaHSjZyLj5AcS014Ss+88g4yGDqRRARE=,tag:oeX1B72CVLdTwLysxmieMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
