apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:4AOzRDpd9N2vXI2lUzQFcRxwHg8a6guuTL2iwb38lGI=,iv:vbbkUU+6LEb1xic+HYo96wT5IINocy/xQGtLeZPcAyw=,tag:xVNB4koh3HN6k7/0NJu+dQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMckIxdzRjUzd2bTZXL2NT
            K2VPUHhxckNxckFnZm5ISlorR0NvN0ZkM0NZCmt3MDhPUEFudnNKTEU5Ym1DeUZq
            TlFwYjVYU3k4bFgwQ2prVGxpQXdZVnMKLS0tIHUvVWlNTCswT3N5U3FnQk56YzFj
            b3VyOWZ2NWtvazNzK0MrbWt4bi9oOUEKnm8bYTZcw8caz7ukXbdRy8LxN+8Syntm
            VdWtR8VMTbs8olSKbdtqSGs8ZAu5BLBHicUbEejT6A8W/TPP/Lx5pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T10:25:36Z"
    mac: ENC[AES256_GCM,data:Z6F7dVZ/rmiWa8ZBDGzAhHnIXLPbb5aw6uNtosdgYNOfZoD3P8HslR6Ra2felV7XkiyG5WmxAsxviRH+hxin7oODiKRV0NWXjEVqipMzcAr41gtYlwQEgHRlWKCaFiOinXtgsm6IzOgtbu6+hKoSwt5wA/QM/S9phAZGqFdv7aI=,iv:Mj7QTVP6xciVHhM2xnO30Gn9tZ5euozHDnTAd0NV7pI=,tag:YCuylcOy9RDdn+Ikmfs5yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
