apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TjSrL/ywbTlbBEr9WZMxbL7kVs9/gCKGSHZ/aInwCgc=,iv:CFM0ylkEGCl6tgn3vvReGNL51ujaQrISHsiXohoHuuI=,tag:YrCxSTX7YeFwxqqziHnfHg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcjhHcnB0eHdqYlJWalJj
            dUJlYXJjdXNKZjM3OXlIWDZJTHRFcHdoNEFzCnlsWTJkTEZoTEFFYmlIdWZQMHNh
            ZE5KMTV2dC9EakVldDBpQnFSL0t5YmcKLS0tIFNheFZYdjNiWlQwZDZvMGduTFFw
            UFZmZUU2am1IQ25TOFhpM3N4RndodEUKVtfp9MqYYT2A5bCIlgSMS3RhjyWfjrEZ
            Dl8gStzCsODgdhUzKRXzAAYT9LjRmTP9fp5boKY0gBJ3M43SKG6Dow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T12:09:21Z"
    mac: ENC[AES256_GCM,data:MSCHC45mfRoDNfbHQ8xfvOgq58OPO0tZ16YtKc1YEsk1nX3b1EWB9hTvd0hgzZQ6zNrzHrgBSc+HucqO0DZfMjp9i/c6BVdmYtoAw4cnxtfZzoaMpY8M5nEe2G7/oefRuEoXZTI9gDA8FBMMbW8jB0mcKdYs0OVSyIaGIlWmptU=,iv:VnW0qW6BcGUnxnLFj8+efvJUi5mrWhpMkMMc2dLyIXw=,tag:XsiSGMYygWektDRY/aLNgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
