apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ZKjxxnfqCTR7V8x11dhK7VMbKyub4WqSKeC+F1ESj/c=,iv:buceNB1rSKM31rRLMFTXqJ0Ca7J2Sc20Uj5OmmlBt5w=,tag:ZGmxBJwlMwrjKwsMCWpsww==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VVhkZ21MNTN1VXRWUmNu
            U2ZFUGptS1pYRUI4QjFhcy84VEs1ckdwR1FvCitEZjRkdjZyMXgrZWVESGttajlF
            V0JjdXZobmxXK2lLaEZuNzcxbWp5TjgKLS0tIGY3cmhHNGdnZXVqS2FmSnhWWjRO
            QXFmVzcvM1ExMXBCeUdiTHhuOVhiU1kKfM4Pl94jMtz1Pi6DldR6OcWkPoteDYoa
            8i7rbetjNkvmOxs2sJvzsOLBvSzOv1QelI9I2/dHPdh0NPvpkjacog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T12:35:56Z"
    mac: ENC[AES256_GCM,data:DG8RJpyLDQm85hMIztNBz48vsAHHgk6E7k6DHHgSpYGoKq5hmpDXRmIrBvUOAr6Q5bYVY9PbeCnGJAyCEDhgEpSD3CBTL+r9X/wdLLYiTqHBwxnQkQnX4UJSmXg0ZO2WnY8MQr4QW9/i5BgBdlTlKjyb2W8s6k2Ikri8vuukVaM=,iv:Luka5gDX7LotDwfPesg9j6x5hRRkBfIWQVe2zjOr+5g=,tag:M0GdCHSYlJP45huPMKO6kA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
