apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:1GL4RCrz2Q32G1wD/yhIfsIAozdhl6D0oILW43ffAvQ=,iv:kUJ5pvANeiCJnu4v0XykszpQETwWEWnJxgXBeBsvZeU=,tag:di2GMOqqnXnzZSL6KpMgEw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNy9OM1R6SlNSdGMxT0R5
            V0VQNmUvQWlsOEJkVi9YbzdSY1V5NHM3b21jCnVjeC9Ia3lTclVzSEhidENjNzZs
            d3BGQzZHbEFxSHl6V1VqaFRjUWVCZ0kKLS0tIGlUOVgzdWR4RXIrb0V2SzltcHZp
            RGFKdDNSeE4ycGxRdWxDT0pySmE1WHcKi+Xh0dQtp7iEem5rnuUr2vuj+9gtULZL
            5Ry1mLg1G/7bX0J40Aiyz4/GYsCapa2IurDo59JBAXU2Umj0pYnfIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-08T11:50:07Z"
    mac: ENC[AES256_GCM,data:7kNfkRfl1W9R8/Ca51woGzq4RfKhTo5fGCEo+Fci+rYakSq3dXWEaJf8od/m0NWZ3V9N1G1is4rckNqmC1Kb06jcBjysELw/IAUQTXxiXv2bVM1Mg/cN/rOqQJEUJMKN9o/vBNjXw9hoG/5YNtgNIQQzRotMpPF2VXOS9zNsuXs=,iv:zrdpgwoex/lCt4OFbMJgr77/OhY3y2ZwmaDCgcZvXW0=,tag:j4g7/gayoFQzqixfRqzBGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
