---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runners-personal
  namespace: gha
spec:
  interval: 15m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    minRunners: 3
    maxRunners: 6
    githubConfigSecret: runner-secret-personal
    githubConfigUrl: https://github.com/alfi0812
    controllerServiceAccount:
      name: actions-runner-controller
      namespace: gha
    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes:
          - ReadWriteOnce
        storageClassName: openebs-hostpath
        resources:
          requests:
            storage: 32Gi
    template:
      spec:
        containers:
          - name: runner
            image: tccr.io/tccr/charts-ci:latest
            command:
              - /home/runner/run.sh
            env:
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"