---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: system-upgrade-controller
  namespace: system-upgrade
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 14.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: docker.io/rancher/system-upgrade-controller
      pullPolicy: IfNotPresent
      tag: v0.15.2@sha256:3e899833afcea9a8788d384ce976df9a05be84636fe5c01ec2307b5bd8fe9810
    workload:
      main:
        strategy: RollingUpdate
        podSpec:
          containers:
            main:
              env:
                SYSTEM_UPGRADE_CONTROLLER_DEBUG: false
                SYSTEM_UPGRADE_CONTROLLER_THREADS: 2
                SYSTEM_UPGRADE_JOB_ACTIVE_DEADLINE_SECONDS: 900
                SYSTEM_UPGRADE_JOB_BACKOFF_LIMIT: 99
                SYSTEM_UPGRADE_JOB_IMAGE_PULL_POLICY: IfNotPresent
                SYSTEM_UPGRADE_JOB_KUBECTL_IMAGE: registry.k8s.io/kubectl:v1.33.1
                SYSTEM_UPGRADE_JOB_POD_REPLACEMENT_POLICY: Failed
                SYSTEM_UPGRADE_JOB_PRIVILEGED: true
                SYSTEM_UPGRADE_JOB_TTL_SECONDS_AFTER_FINISH: 900
                SYSTEM_UPGRADE_PLAN_POLLING_INTERVAL: 15m
                SYSTEM_UPGRADE_CONTROLLER_NAME: system-update-controller
                SYSTEM_UPGRADE_CONTROLLER_NAMESPACE: system-upgrade
    persistence:
      etc-ssl:
        type: hostPath
        hostPath: /etc/ssl
        hostPathType: DirectoryOrCreate
        readOnly: true
      etc-pki:
        type: hostPath
        hostPath: /etc/pki
        hostPathType: DirectoryOrCreate
        readOnly: true
      etc-ca-certificates:
        type: hostPath
        hostPath: /etc/ca-certificates
        hostPathType: DirectoryOrCreate
        readOnly: true
    serviceAccount:
      system-upgrade:
        enabled: true
        primary: true
      talos:
        enabled: true
        primary: true
    rbac:
      main:
        enabled: true
        primary: true
        serviceAccounts:
          - system-upgrade
        subjects:
          - apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
        