apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: alfi
    namespace: flux-system
spec:
    interval: 5m0s
    url: https://alfi0812.github.io/helm-charts/
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzY3l1dXVmV0VHbFFmblNT
            clhLY3NmV0FxTGY1S241dlNoczJlZUF3MjEwCmdFcmU1TkhaRkx2S0s2eG1KUmls
            bHh1U3FaeGRtbmhIeWp2MXplWENZNkUKLS0tIFdPMkVRSHR0cHF6M1NEWlhTQWRo
            MzJMVHJaWmNBMG1mTDZGTzZSakRUUnMKqEfZeo+6U2M6mQiqUiVsCRoRtQGBjwK/
            dty8NS3I6M8+tSdzaU+oy/g43s3bFQjyLYiowJfmEtl//BQqY4uP4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T19:12:24Z"
    mac: ENC[AES256_GCM,data:vjfl65GS9JtGbsB9hCvmg5LlRV7BFKk27BwrxN465DtMQ8F3NNgRS6OKejxmuB0zx32H1Nv2vDGr7aDXEvQpj8TQ2L4mlI6h3bsxqAS+jehZ0HxbJ7hnEPHobQwVq/2XAEhc89Cbxl8W9LIh55Wr1NRvY4cA12GqclJydV4cqIg=,iv:4MJt1L0GeHoquBB2UvE3Vudc5fs7Vu5Hx95K8RPBgsY=,tag:hcDP9xju9GPwyTOIfPRtbw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
