apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: alfi
    namespace: flux-system
spec:
    interval: 5m0s
    url: https://alfi0812.github.io/helm-charts/
    secretRef:
        name: ENC[AES256_GCM,data:MjS4tAK7HILVfKo=,iv:CAZK0JmGOMc3Q7nzAoUGoYXPmdaXQXOkTOo+HuuHHJo=,tag:IHy3uDUYbgyAIEUViA4k/Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNUIyWmswTnVxbWVFbGc4
            OVZIeGx5am5Fbk1DRWMwT29wK3A3NmRKRjAwCm1LcXpMaWFOakVZYTFmN2hjVkxl
            d0pFU2NrSmpYN21PVkVPeHRzanJUWEkKLS0tIHM3cC9DY3JHRHFIYXI4OXRJdHhU
            M3oyWkVYeGZIWmpxeURSMHNLMVJlU3cKKzYU8bzICIlBDTQSxRWT1QJlwxHhED8U
            +xAGHNP090pAsD7Wj6QVDgrSy7vF7b7jYnmLp2EsJiz+iHE+nwiXlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T18:23:59Z"
    mac: ENC[AES256_GCM,data:KdASm/ETxHXispfemrjjVOHbgkS5Yg474MgQV541/G0WETwo5wSi9sANA5TipHdtB4AEgMiIvZ7QNWhjCOOkhuUY2a+l1ynCmRgFgQDGjR4H9Ss8YE05tMvGZRCPHr9Dm7IbV/saYpaa2SJ5LT7dV2QFa77hIaRj8fmPKjPn0Dk=,iv:KPkKk5AO5F5Wm7OiNxHpYGOyS49Ey1S3tEywOjFbDZE=,tag:7B9s7sysRBneJ+NOvqpcxg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
---
apiVersion: v1
kind: Secret
metadata:
    name: github-user
    namespace: flux-system
stringData:
    username: ENC[AES256_GCM,data:x9omfzpEw7k=,iv:+EC3eS8FMM4H31p3ctM/yp1pFHAWBDdFORtLNhQHUbo=,tag:vQTRCfNcs/21o7w7rAHPfg==,type:str]
    password: ENC[AES256_GCM,data:xvDsyTuQXUDMB1zBeH+qeZvc0LFjcoDm6FBj138BXqLusFJEJltzEw==,iv:yl0HdXQdCApk1fwc65flk5RyfuKYEYsH9wAAcXSIu8I=,tag:7EECUg7ZQiizzB5edK7NXg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1s0wp87jw9eumgu0r08qah0hn8zwk5ge29hs0pnqcs2895vp9genqhrmx6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNUIyWmswTnVxbWVFbGc4
            OVZIeGx5am5Fbk1DRWMwT29wK3A3NmRKRjAwCm1LcXpMaWFOakVZYTFmN2hjVkxl
            d0pFU2NrSmpYN21PVkVPeHRzanJUWEkKLS0tIHM3cC9DY3JHRHFIYXI4OXRJdHhU
            M3oyWkVYeGZIWmpxeURSMHNLMVJlU3cKKzYU8bzICIlBDTQSxRWT1QJlwxHhED8U
            +xAGHNP090pAsD7Wj6QVDgrSy7vF7b7jYnmLp2EsJiz+iHE+nwiXlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T18:23:59Z"
    mac: ENC[AES256_GCM,data:KdASm/ETxHXispfemrjjVOHbgkS5Yg474MgQV541/G0WETwo5wSi9sANA5TipHdtB4AEgMiIvZ7QNWhjCOOkhuUY2a+l1ynCmRgFgQDGjR4H9Ss8YE05tMvGZRCPHr9Dm7IbV/saYpaa2SJ5LT7dV2QFa77hIaRj8fmPKjPn0Dk=,iv:KPkKk5AO5F5Wm7OiNxHpYGOyS49Ey1S3tEywOjFbDZE=,tag:7B9s7sysRBneJ+NOvqpcxg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
