---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Automerge area/github"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths: [".github/**"]

jobs:
  automerge-and-approve:
    name: Automerge and Approve Area Github
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@7961b8b5eec56cc088c140b56d864285eabd3f67 # v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          UPDATE_RETRIES: 12
          UPDATE_RETRY_SLEEP: 60000
          MERGE_METHOD: squash
