name: "Pull Request: Validate"

on:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  # cancel-in-progress: true

jobs:
  pr-changes:
    name: Collect PR changes
    runs-on: ubuntu-latest
    outputs:
      addedOrModified: ${{ steps.collect-changes.outputs.changesDetected }}
      addedOrModifiedFiles: ${{ steps.collect-changes.outputs.addedOrModifiedFiles }}
      addedOrModifiedCharts: ${{ steps.collect-changes.outputs.addedOrModifiedCharts }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Collect changes
        id: collect-changes
        uses: ./.github/actions/collect-changes

  charts-lint:
    uses: ./.github/workflows/charts-lint.yaml
    needs:
      - pr-changes
    with:
      checkoutCommit: ${{ needs.charts-changelog.outputs.commitHash }}
      chartChangesDetected: ${{ needs.pr-changes.outputs.addedOrModified }}
      modifiedFiles: ${{ needs.pr-changes.outputs.addedOrModifiedFiles }}
      modifiedCharts: ${{ needs.pr-changes.outputs.addedOrModifiedCharts }}
  charts-test:
    uses: ./.github/workflows/charts-test.yaml
    needs:
      - pr-changes
      - charts-lint
    with:
      checkoutCommit: ${{ needs.charts-changelog.outputs.commitHash }}
      chartChangesDetected: ${{ needs.pr-changes.outputs.addedOrModified }}
      modifiedCharts: ${{ needs.pr-changes.outputs.addedOrModifiedCharts }}
  finished:
    name: Finished PR Tests
    runs-on: ubuntu-latest
    if: always()
    needs:
      - pr-changes
      - charts-lint
      - charts-test
    steps:
      - name: Check Results
        run: |
          if [[ "${{ needs.pr-changes.result }}" != "success" || \
                "${{ needs.charts-lint.result }}" != "success" || \
                "${{ needs.charts-test.result }}" != "success" ]]; then
            echo "One or more jobs failed!"
            exit 1
          else
            echo "All jobs succeeded!"
          fi
